### ISSUE TITLE
Unclear problem message in editor

### ISSUE THREAD

**Issue by minglho** [isle-project/isle-editor#1132]
In the screenshot below, you can see a problem identified by the editor. The message is unclear, but everything renders fine.
![image](https://user-images.githubusercontent.com/13249661/87126940-ee021c80-c241-11ea-9c35-8298da4266ff.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.57.1

**Comment by Planeshifter** [comment]
The error message refers to a missing space between the closing `"` of the raw attribute of the `<Text` component and its closing `/>` bracket. The code is fine as-is though, the message is merely about a stylistic convention enforced by the editor.
