### ISSUE TITLE
Odd Control Behavior in Data Explorer

### ISSUE THREAD

**Issue by minglho** [isle-project/isle-editor#1135]
In the video link below, I show you the odd behavior of moving a window in the background, which occurs when I try to bin quantitative variable into categorical under Transform in the Toolbox.

https://www.awesomescreenshot.com/video/375873?key=41f3efc6870cd81f83f294c38ea9a20e

**Comment by Planeshifter** [comment]
Thanks for reporting, but this issue should have already been fixed. Was this data explorer uploaded a while ago? If the error persists after re-uploading, would you be able to please point me to the uploaded lesson where the problem occurs? Thanks!
