### ISSUE TITLE
Box Select in Histogram not highlighting correctly

### ISSUE THREAD

**Issue by minglho** [isle-project/isle-editor#1137]
I created a histogram in the [Heart Disease Data Explorer](https://isle.stat.cmu.edu/data-explorers/heartdisease/). Then I used Box Select to select two bars of the histogram. You can see how the histogram was created and which two bars were selected in the diagram below.

![image](https://user-images.githubusercontent.com/13249661/87236207-f1f58200-c39a-11ea-8011-f8ac9967a803.png)

As you can see, there is a dashed box indicating which two bars I wanted. However, only the left of the two bars is shown as selected in deeper blue. Yet, in the data table, you can see that the range of values included for the variable Age is actually wider than the two bars I intended to select. This tells me the box select function includes the x-values enclosed by the box, not just the highlighted bar nor the bars whose based are completely enclosed in the dashed box. If that's the intended functionality of the Box Select function, then perhaps the deep blue highlight should extend our to partially bars to avoid having the visual not matching the actual observations selected, as shown below:

![image](https://user-images.githubusercontent.com/13249661/87236335-e4d99280-c39c-11ea-8bdc-931e435ad13a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by Planeshifter** [comment]
Yes, currently only the x-axis bounds of the selection box are used for filtering the observations in the data table. So the filtered observations in the table won't necessarily match the blue-shaded bar(s), yes. Will take a closer look and investigate possible solutions.

**Comment by Planeshifter** [comment]
The selection handling has now been refactored to ensure that only the range implied by the shaded blue bins is used to calculate the range. So in a case like this:

![image](https://user-images.githubusercontent.com/1913638/88447195-8b428080-cdfe-11ea-8b55-aa41c642e239.png)

the dataset will be filtered to only the observations with `AirTime` values between 160-179. 

In addition, we now restrict the ability to draw arbitrary select boxes and only allow horizontal selection to ensure that one cannot select bins that are not adjacent to each other like in this example:

![image](https://user-images.githubusercontent.com/1913638/88447231-dbb9de00-cdfe-11ea-8113-bc9a7a046070.png)

as such a selection cannot be mapped to the data table filters right now. 

These changes should resolve any inconsistencies and cause the observations in the blue shaded bins to correspond to the filtered view in the data table.

**Comment by Planeshifter** [comment]
Closing as the resolution of this issue is part of today's release. Please leave an additional comment in case the issue was not resolved properly and we will revisit the problem.
