### ISSUE TITLE
Data Display in Data Explorer

### ISSUE THREAD

**Issue by minglho** [isle-project/isle-editor#1138]
I uploaded a lesson, which is located at https://isle.kymetis.com/Fa20MTH43/gastricbands/.
As you can see above, the data columns are not lined up with its headers.

![image](https://user-images.githubusercontent.com/13249661/87236821-9d560500-c3a2-11ea-87a8-362537332504.png)

**Comment by Planeshifter** [comment]
In the most recent version of the data table, that behavior occurred for datasets with few variables whose cells wouldn't span the whole table width. Pushed a fix (https://github.com/isle-project/isle-editor/commit/8dc545af035c9229be47f715ad6522af08f0ee50) that should improve the table display in this case.

**Comment by Planeshifter** [comment]
Closing as this issue is part of today's release. Please leave an additional comment in case the issue was not resolved properly and we will revisit the problem.
