### ISSUE TITLE
accept multiple numerical answers

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#1144]
Request to update numerical answer feature to accept multiple answers, or maybe even ranges of answers.  Motivation for the request is:  Students who round to different decimals; or give answers as percent instead of decimal.

**Comment by Planeshifter** [comment]
The next release will allow one to specify multiple correct answers per commit abc4818a00e4a291849c537187f3bd660ccf7211. 

I am not convinced the ability to specify a range of correct answers is necessary given that we already can specify to what digit after the decimal point a response has to match the supplied solution. Or did we encounter an instance where the ability to specify a range of solutions would have been useful?

**Comment by gweinberg** [comment]
Awesome.  No, I'm not specifically aware of a case when a range of answers was needed.  We have encountered cases where there were various correct answers due to rounding.

**Comment by Planeshifter** [comment]
Closing as this issue is part of today's release. Please leave an additional comment in case the issue was not resolved properly and we will revisit the problem.
