### ISSUE TITLE
consistent ordering of levels in frequency tables grouped by

### ISSUE THREAD

**Issue by jricoiii** [isle-project/isle-editor#1146]
**Is your feature request related to a problem? Please describe.**
When using the frequency table with group by, would it be possible that the levels appear in the same order for each grouping?

**Describe the solution you'd like**
Would like to see consistent column headers in same order across the table groupings

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/50716185/87487474-97566300-c5f2-11ea-9229-8874c703477e.png)

**Comment by Planeshifter** [comment]
Hmm, we could order the categories alphabetically in the table by default?

It is already possible to specify an ordering for the categories, which will be picked up by the various functions. See the following example:

```
---
title: "Diamonds"
removeStatusBar: true
require:
    diamonds: "https://isle.stat.cmu.edu/data-explorers_diamonds.json"
    diamondsInfo: "https://isle.stat.cmu.edu/data-explorers_diamonds_info.json"
state:
---

<DataExplorer 
    id="diamonds"
    data={diamonds} 
    dataInfo={diamondsInfo}
    categorical={[
        factor( 'cut', [ 'Fair', 'Good', 'Very Good', 'Premium', 'Ideal' ] ),
        factor( 'color', [ 'D', 'E', 'F', 'G', 'H', 'I', 'J' ] ),
        factor( 'clarity', [ 'I1', 'SI2', 'SI1', 'VS2', 'VS1', 'VVS2', 'VVS1', 'IF' ] )
    ]}
    quantitative={['price','carat','x','y','z','top','body']}
/>
```

**Comment by jricoiii** [comment]
Thanks.  I’ll try that.  The factors were ordered in R, but don’t think that holds when written to JSON.  So guess I can always reorder them when adding to the data explorer.

**Comment by jricoiii** [comment]
I think it would still be a good idea to have categorical variable to have a default ordering, then at least when tables and plots are constructed they will have the levels in the same order.  If you can do that - it would be great.

**Comment by jricoiii** [comment]
Wondering if set as factor - but don't specify an order - does a default ordering occur?

**Comment by Planeshifter** [comment]
Agreed, we should have a default ordering (alphabetical?). That's not currently implemented but definitely has high priority.

**Comment by jricoiii** [comment]
I just noticed that when binning a numerical to categorical the levels are not set to be in any order...
Seems like this definitely should be an ordered factor.
![image](https://user-images.githubusercontent.com/50716185/87999426-99ffff00-caaf-11ea-8e89-91d03ea9ab88.png)

**Comment by jspm-kymetis** [comment]
Suggestion - alphabetize the order by default, can reset if needed by transformation and renaming categories

**Comment by Planeshifter** [comment]
Outputs generated through the binning transformation tool now have the correct ordering.

In addition, any grouped statistics output or table will show the categories by default in alphabetical order (unless they are factor variables as described above with an inherent ordering).

Closing, but please leave an additional comment in case the issue was not resolved properly and we will revisit the problem.
