### ISSUE TITLE
additional options for contingency table

### ISSUE THREAD

**Issue by jricoiii** [isle-project/isle-editor#1147]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
I would like to be able to see a nice concise tabulation with counts and percentage in the same table (like in janitor:tabyl)
Or at least can I have the option for the contingency table to have percentages calculated across the row (instead of across all cells)

**Describe alternatives you've considered**
There are many ways around this, but each has its issues...I would my students to be able to quickly see percents and counts

**Additional context**
This is what I would like to be able to generate
![image](https://user-images.githubusercontent.com/50716185/87487901-c0c3be80-c5f3-11ea-9a1b-127b067155d6.png)
R Code

```{r}
acs_clean_sample %>%
  tabyl(sex, marital_status) %>%
    adorn_totals(c("row")) %>% 
 
    adorn_percentages("row") %>% 
    adorn_pct_formatting(digits=1) %>% 
     adorn_ns() %>% 
  
  kable(booktabs = TRUE) %>%
    kable_styling(bootstrap_options = "striped",
                  full_width = T, 
                  position="left")
```

Currently I can make this in ISLE - actually using frequency table instead
![image](https://user-images.githubusercontent.com/50716185/87487947-e5b83180-c5f3-11ea-9739-bab68928501d.png)
or

**Comment by jricoiii** [comment]
In my instructions to my students in my lesson - this is what I am having to say;

In order to a contingency table with counts and row percentages, you will need to create three tables and then combine the information in the Report tab of the Data Explorer 
        1.  First table is a base contingency table (counts only) 
                - *Row Variable* is the explanatory variable 
                - *Column variable* is the response variable
        2.  Second table is base contigency table with;
                - *Group By* the *Row Variable* 
                - Click on *Relative Frequency* 
                - Obtains the row percentages for your explanatory's variable's levels
        3.  Third table is relative frequency table of the response variable 
                - Obtains your overall percentages for the response variable (i.e., the percentage for the bottom row of your first table)

**Comment by minglho** [comment]
I second that there should be more options to display different percents in the contingency table, and I think we should be able to display multiple tables in one. Here is an example from StatCrunch, showing options menu for contingency table and the output:
![image](https://user-images.githubusercontent.com/13249661/87610991-c1c02300-c6bb-11ea-98b4-5eddbd034b1d.png)

**Comment by Planeshifter** [comment]
The data explorer in today's release now has the option to calculate percentages across rows and columns, respectively. Please let me know what you think and if you have further suggestions.

**Comment by Planeshifter** [comment]
Closing this for now. Please feel free to reopen if you require additional functionality for the contingency table.
