### ISSUE TITLE
mosaic plot left side levels not fitting (since written vertical)

### ISSUE THREAD

**Issue by jricoiii** [isle-project/isle-editor#1148]
**Describe the bug**
Not sure if really a bug, but output is unclear

**To Reproduce**
basic mosaic plot

**Expected behavior**
labels on vertical axis are written vertically which cause them to overlap and become un-readable

**Screenshots**
![image](https://user-images.githubusercontent.com/50716185/87491619-7a735d00-c5fd-11ea-83a5-cfbf77b5af71.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version 0.58

**Additional context**

**Comment by Planeshifter** [comment]
There is now a select menu that allows one to switch between various axis rotations:

![image](https://user-images.githubusercontent.com/1913638/88447955-be890d80-ce06-11ea-8935-d8584b7801dc.png)

This should give one enough flexibility as long as the variables do not have an enormous number of categories.

Going forward, we will replace this plot component, which currently uses R code evaluated on a remote server, by an interactive plot like for the others. Having this in mind, it might be useful to for now just collect any more improvement suggestions and implement them once we move to a new implementation.

**Comment by Planeshifter** [comment]
Closing as part of today's release. Please leave an additional comment in case the issue was not resolved properly and we will revisit the problem.
