### ISSUE TITLE
Unable to click on last two buttons on Plotly modebar 

### ISSUE THREAD

**Issue by jricoiii** [isle-project/isle-editor#1154]
**Describe the bug**
Red Box with Filters X covers the last 2 options (one which is the full screen option - which is a feature I will need while teaching)
(Maybe you could remove 2 buttons that aren't commonly used - or change the order?)

**To Reproduce**
Just make any plot in the Data Explorer

**Expected behavior**
Be able to hover over the modebar and click on any/all buttons

**Screenshots**
![image](https://user-images.githubusercontent.com/50716185/87609808-70fafb00-c6b8-11ea-8ed6-915e22982c8f.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Additional context**

**Comment by Planeshifter** [comment]
We refactored the design to avoid any overlap.

Closing, but please leave an additional comment in case the issue was not resolved properly and we will revisit the problem.
