### ISSUE TITLE
Group related icons together

### ISSUE THREAD

**Issue by minglho** [isle-project/isle-editor#1155]
![image](https://user-images.githubusercontent.com/13249661/87613026-fbdff380-c6c0-11ea-8210-5aff7d9ed21d.png)

Above is the toolbar in Sketchpad. Notice that the brush icon and the brush width icon are together, but the brush color icon is quite far apart from them. It would make more sense move them together; see blue arrow as an example. I noticed that the color icon is for both text and brush, so putting it in between the two groups would make sense.

**Comment by Planeshifter** [comment]
The suggested change will be incorporated in the next release per commit 1bd6273231dade5671f89335f3ed9c20d16aea4d.
Thanks for the suggestion!

**Comment by Planeshifter** [comment]
Closing as this issue is part of today's release. Please leave an additional comment in case the issue was not resolved properly and we will revisit the problem.
