### ISSUE TITLE
Additional summary statistics for numerical variables

### ISSUE THREAD

**Issue by jricoiii** [isle-project/isle-editor#1164]
**Is your feature request related to a problem? Please describe.**
NA

**Describe the solution you'd like**
Would like to have options to get a full 5 number summary from **Toolbox's Summary Statistics** .  Currently Q1 and Q3 are not available.  (unless 

Additionally, I would like to be able to obtain any percentile (say 90th?  99th?...)

**Describe alternatives you've considered**
haven't really tried to get these values, beside making a boxplot...

**Additional context**

**Comment by jricoiii** [comment]
Would also like the opportunity to a second group by option in summary statistics (as box plots has)
![image](https://user-images.githubusercontent.com/50716185/87980592-b9376600-ca88-11ea-87d6-c09da7ff7eaf.png)

![image](https://user-images.githubusercontent.com/50716185/87980343-4cbc6700-ca88-11ea-9fd0-824f02d9be31.png)

**Comment by Planeshifter** [comment]
The next release of the editor will contain both the option to calculate the quartiles as well as any percentile. In addition, it is now possible to group the statistics by up to two variables and also to calculate a selected set of statistics for multiple variables at once.

**Comment by Planeshifter** [comment]
Closing for now.

Gordon Weinberg created an issue to discuss further suggestions on the summary statistics tab or you could always create a new issue in case you encounter any other bugs or limitations. Thanks!
