### ISSUE TITLE
brainstorming enhancements to "statistics" tab

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#1165]
Reading the request for five-number summary got me thinking about the "statistics" tab; so here are some discussion topics for possible enhancements to toolbox -> statistics -> statistic(s):

1) Currently, the choices in the dropdown seem to be ordered by topic, although not explicitly; how about explicit topic headings inside the dropdown, like:
"measures of location", "measures of variation", "measures of relationship", "measures of shape;" and then the actual selectable statistics choices would be indented (and the headings would need to be in a different font, maybe italics and grey or something, so it would be clear the headings aren't selectable).

I don't know where five-number summary would go if it's added (referring to another posted request); I guess it would need to go under its own sub heading, probably after the "measures of location" subsection and before "measures of spread" subsection.

2) a toggle inside the dropdown, to toggle between "grouped by topic" and "alphabetic list"; if "alphabetic list" is toggled, then all the summary statistics get listed alphabetically.

3) in the pulldown, some popups upon mouseover of the various statistics choices, giving a brief definition or explanation, maybe the formula, and maybe brief statistical cautions about their use if appropriate (e.g., when mousing over "correlation," the popup could be something like, "computes the sample Pearson correlation coefficient" [then maybe a formula, or maybe a link on the popup to a page with the formula], and then maybe "may be inappropriate for nonlinear relationship" or something like that.  (I'd be happy to help write some popups)

Not sure if these would be useful or doable, figured I'd throw it out there to see what people think.

**Comment by Planeshifter** [comment]
On this OkCupid explorer, there is a draft for how such a re-organization of the statistics could look like:

**Comment by gweinberg** [comment]
![image](https://user-images.githubusercontent.com/31780210/89685761-fb570900-d8ca-11ea-971e-4917ffc136df.png)

**Comment by gweinberg** [comment]
"You could create a pull request"

  You're going to have to explain what a pull request is.


https://github.com/isle-project/isle-editor/blob/master/app/components/data-explorer/statistics_descriptions.json

    What do I do with this?  Do I copy this into the ISLE editor?  What's a json?

**Comment by Planeshifter** [comment]
Here is a new iteration with the selected options being still shown in the dropdown menu and no default statistic:

https://isle.stat.cmu.edu/demonstrations/okcupid-summary-stats/

We could certainly remove other pre-selected fields as well, e.g. the variable one in summary statistics.

**Comment by gweinberg** [comment]
Nice!  And selecting it again removes it, nice.
Yeah I've always found having the top thing pre-selected in the ISLE widgets awkward; I suspect it confuses some students.

**Comment by Planeshifter** [comment]
With the change in 40d92dba9b53199c595b24f85fd554083eb34497, a five-number summary can be selected with a single click in the statistics menu starting with the next release.

I investigated adding a toggle between "grouped by topic" and "alphabetic list", but this would be cumbersome to implement and also make the interface more complicated. My sense is that in case you are looking for a specific statistics, one can already start typing it to filter the available options. In light of this, an additional "alphabetical list" functionality feels like overkill.

Closing this issue as I believe all other suggestions are now incorporated. Thanks again for providing these!

Please feel free to re-open in case I missed anything.
