### ISSUE TITLE
Filter Options (removal of individual vs restore original dataset)

### ISSUE THREAD

**Issue by jricoiii** [isle-project/isle-editor#1168]
**Is your feature request related to a problem? Please describe.**
One issue is that I can't wrap multiple histograms when grouping (histograms are always created as overlays).
Other is just during EDA, I am having to redo filtering multiple time when analyzing a data set.

**Describe the solution you'd like**
Would be nice to be able to selectively remove a individual filter.  Maybe the Data Explorer could have a list of individual filters and then the user could select the individual filter they would like to remove.  I am running into an issue where I am having to restore to original, only to redo my filters.  

**Describe alternatives you've considered**

**Additional context**
Here's an example; 
Filtered:
employment_status: ["employed"]
AGEP: {"min":19,"max":21}
educational_attainment: ["GED/HS"]

I would like to remove the GED/HS  to look just at Some College, only way to do it is Restore and then do all the filter again....
![image](https://user-images.githubusercontent.com/50716185/88002106-8f953380-cab6-11ea-8829-32ba3c684a6e.png)

**Comment by Planeshifter** [comment]
Idea: We will add buttons to selectively remove filters.

**Comment by Planeshifter** [comment]
In the next version of the editor, filters can now be individually removed:

**Comment by Planeshifter** [comment]
Closing for now. We can always re-open the issue if not solved satisfactorily or you have additional feedback on the filtered dataset behavior.
