### ISSUE TITLE
LearnSampleCLT - wish list for options/features

### ISSUE THREAD

**Issue by jricoiii** [isle-project/isle-editor#1213]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
I would like the following for sampling
- be able to full-screen enlarge histogram of sample means/proportions
- be able to set x-axis (currently only a default axis)
- increase sample size to 2000 (currently set to max of 500)
- (also - just a question - but when I hover over the created histogram - I see the bin size in black and a number in blue (what is that number suppose to represent?
![image](https://user-images.githubusercontent.com/50716185/89219731-3385e100-d585-11ea-96c9-470d9c4c65d4.png)

**Describe alternatives you've considered**
n/a

**Additional context**

**Comment by Planeshifter** [comment]
Going forward, it's now possible to draw samples up to a size of 2,500 with this component. The histogram has additional buttons letting one view it in fullscreen and to change the x-axis range. The hover tooltip now has the format `(x-range, density value)`.
