### ISSUE TITLE
Issue with One Sample Proportion Hypothesis Test

### ISSUE THREAD

**Issue by jricoiii** [isle-project/isle-editor#1231]
**Describe the bug**
The test will use previous setting for success (from the first variable listed) if the user does not select a different level for success.

**To Reproduce**
1. Go to 'Test.'
2. Click on 'One Sample Proportion Test.'
3. Click to change the variable
4. Click Calculate
5. You'll see the toolbox tries to calculate based on the success listed on the previous variable.
6.  This will happen again if you choose another variable and don't change the success 

**Expected behavior**
Should calculate based on the success in the toolbox for that variable

**Screenshots**
00101 is not a level for sex
![image](https://user-images.githubusercontent.com/50716185/89720681-b2b25500-d989-11ea-9b7d-cb22b026b30b.png)

now i change the success to male (and it works)
![image](https://user-images.githubusercontent.com/50716185/89720687-d5446e00-d989-11ea-8bb8-ced921f32053.png)

now i change variable to citizenship_status (and it try to calculate for success being male)
![image](https://user-images.githubusercontent.com/50716185/89720699-07ee6680-d98a-11ea-9566-35d3d4aa90df.png)

**Desktop (please complete the following information):**
 - OS: window 10 
 - Browser chrome
 - Version 

**Smartphone (please complete the following information):**
 - Version 0.60.1

**Additional context**

**Comment by Planeshifter** [comment]
Thank you for filing this issue!

A patch is included in 06563934b5980de7573325c4e98ec14252bc096d and will be part of the next editor release.
