### ISSUE TITLE
faceted histograms

### ISSUE THREAD

**Issue by jricoiii** [isle-project/isle-editor#1249]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Instead on only being able to overlay histograms, could we have an option for faceted histogram

**Describe alternatives you've considered**
the alternative is to create 2 or more histograms, but to do so you will need to filter for each level of your categorical (which would take some time).

**Additional context**
When we study quantitative variables, we often want to compare histogram and boxplots.  Although the overlays are nice (and do a pretty good job when only grouped by a binary categorical), then tend to not be useful for more than 2 levels.

**Comment by Planeshifter** [comment]
It's now possible to create facetted histograms as an alternative to the ones with overlaid bars.
