### ISSUE TITLE
Add data labels to slider input

### ISSUE THREAD

**Issue by sacole167** [isle-project/isle-editor#1253]
Would be good to be able to attach data labels to the end points of slider inputs. E.g., 0 . . . 1; or 1000 . . . 1,000,000; or "less stringent . . . more stringent"; or "more false alarms . . . more misses"

**Comment by Planeshifter** [comment]
4ef5e8232c83bd8915d31c5342937865070a7ef4 adds minimum and maximum labels to the slider inputs, which can be customized by setting the `minLabel` and `maxLabel` properties, respectively.
