### ISSUE TITLE
Binning Num to Cat - error when NAs present

### ISSUE THREAD

**Issue by jricoiii** [isle-project/isle-editor#1257]
**Describe the bug**
When using the Toolbox's Transform for Binning Numerical to Categorical , NA's get treated as values (probably infinity).

**To Reproduce**
From Page 5 of https://isle.kymetis.com/ohlone_2020_collab/06_Sampling_Aug04/
1. Go to 'toolbox'
2. Click on ''bin categorical to numerical'

**Expected behavior**
The NA's should stay NA, not bin into the highest level [x,infinity)

**Screenshots**
![image](https://user-images.githubusercontent.com/50716185/90286584-0a8a0980-de2b-11ea-8d77-3bd42605fd7f.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Planeshifter** [comment]
Thanks for reporting this issue! Commit 7f274c5d7065bfe9904435d9661be0071c12825e contains a fix, which will be included in the next release.
