### ISSUE TITLE
on dashboard, need to navigate to different ISLE course and then back to see changes

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#1270]
Not sure if this is a bug?  On Firefox (on Win10), in order to see changes on my ISLE dashboard (e.g., I've just uploaded a new lab and I want to view it), neither shift+reload nor ctrl+reload nor alt+reload make it appear; I have to navigate to a different ISLE course and then navigate back, to see the change.  [And in general I think this is also the case to see updates of student progress.]  

This might not be a bug (we've discussed how, currently, ISLE doesn't auto-refresh, to save browser memory); and I don't remember if we've discussed a different keyboard combination that would refresh as needed.  But just in case, I figured I'd log it here.

**Comment by Planeshifter** [comment]
Closing this issue as the dashboard now pulls in the most recent lessons whenever the page is refreshed / reloaded.
