### ISSUE TITLE
popup ordering on barchart should match ordering of bars; and request for popup enhancement

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#1272]
Two requests:

1. A particular thing I noticed when replying to issue #1149; I just experienced it again so I figured I'd log it as a separate issue:

When mousing over bars on a bar chart:

a) the popup should, I think, be per bar, rather than a top-to-down whole set of values.  I.e., you should be able to mouse over a given bar, and it should pop up the value just for that bar.

b) barring (a), if we keep it as a top-to-down set of popped up values, than the the top-to-down ordering should match the left-to-right ordering of the bars.  Currently it doesn't.  It seems like it currently re-orders them numerically like a Pareto chart if the category names aren't text strings (which makes corresponding them to the plot very confusing), or else it mostly (but not entirely?) orders the pop ups in the order of the categories if the category names are text strings (but it's still glitching in strange ways).

e.g., in the following screenshot, the popped up values have been re-ordered from largest to smallest.  That makes it very confusing to match a value to a bar, they should be listed in the same left-to-right order of the bars on the plot:

![image](https://user-images.githubusercontent.com/31780210/91081010-74b56200-e614-11ea-9aa2-691288f023bc.png)

(that's from the data={hcv} dataset, bargraph -> status given gender)

The popped up values should be in the same order as the category names.  [I'm guessing it didn't attempt to order the popped up values by the Status category names because the category names in that dataset were just code numbers? ]

Ideally, like this:
![image](https://user-images.githubusercontent.com/31780210/91083019-9532eb80-e617-11ea-800a-535d2d947325.png)

Or at the very least, the popup values should be ordered top-to-bottom in the same order that the bars are left-to-right on the plot.

But even in cases where there are text strings for the category names, the ordering of the pop up is still not entirely correct; see, for instance:

![image](https://user-images.githubusercontent.com/31780210/91081848-c3afc700-e615-11ea-989a-1a03ea42e339.png)

(That comes from the OKCupid dataset if I recall correctly)
 

2.  The Y label on those plots doesn't match the way the values are shown.  The popups are showing decimals (i.e., they're showing **proportions**), but the Y axis is labeled "Percentage" (which would be values between 0 and 100).  It should either show decimals upon popup in which case the Y axis should be changed to say "proportion," or else the Y axis should remain labeled "percentage" in which case the popup values should be changed so that, for instance, instead of 0.20, it would read "20".  [It's probably better to have it be decimals and "proportion", since a popup value like "20" could be confused with group size.]

**Comment by Planeshifter** [comment]
The bar chart now displays "Proportion" instead of "Percentage" on the y-axis and the hover information is displayed on a per-bar basis.
