### ISSUE TITLE
bug in editor 0.62.1 (windows)

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#1273]
When using toolbox on the rendered side of the editor, the menu controls ("Export," "Setting", etc; "show line buttons", etc) go away, and a white bar appears at the bottom of the editor screen:

![image](https://user-images.githubusercontent.com/31780210/91093757-d92dec80-e627-11ea-9def-5aa806ff0122.png)

The bug may be related to the fact that I've got my Windows desktop set to display "text, apps, and other items" at 300%, because it here's how it happens:

* Line buttons off, automatic update off.
* On the rendered side, toolbox -> plots -> pie chart

When I do that, you can see that the bottom of the toolbox is already slightly below the bottom of my editor window:

![image](https://user-images.githubusercontent.com/31780210/91094917-79384580-e629-11ea-9e76-20111c3c2752.png)

* then, in that configuration, when I pull down the "variable" menu, that's exactly when the bug happens, I think it's trying to somehow make more space for the menu, and the bar with all the controls at the top of the editor goes away, and a whitespace bar (of presumably equal size) appears appended to the bottom of the editor:

![image](https://user-images.githubusercontent.com/31780210/91095123-d207de00-e629-11ea-9b47-245b71ba8814.png)

Ctrl+S still saves, and if I quit the file and re-open, it's fine.

**Comment by Planeshifter** [comment]
This problem is solved with the refactoring in 3000f9b5b8395ce5312156dba982a6ac79c56cb9.
