### ISSUE TITLE
Bar Plots with a Group by Variable

### ISSUE THREAD

**Issue by jricoiii** [isle-project/isle-editor#1274]
**Describe the bug**
The Bar Chart is not working for one of my lessons (I have not checked any other lessons).  Although in earlier compiled (from previous versions of the editor the bar chart did work).  It stops working (won't even generate when I add a group by variable).  When a graph does get created it is just blank.  Thought it could be null values (filtered so no null values exist and still no graph)

using the following lesson  https://isle.kymetis.com/ohlone_2020_collab/02_Relationships_Categorical/

![image](https://user-images.githubusercontent.com/50716185/91114377-9f1b1580-e63c-11ea-8f9b-490e55714668.png)

**To Reproduce**
1. Go to 'Bar Plot.'
2. add a group by variable'
3. Generate 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
chrome on PC

**Additional context**

**Comment by Planeshifter** [comment]
This regression, which occurred in response due to flipping the variables per https://github.com/isle-project/isle-editor/issues/1149, is now solved per commit https://github.com/isle-project/isle-editor/commit/d6a27e8ec2dc92cfe389bde6860d2a03a01561c5. 
Thank you for reporting this issue!
