### ISSUE TITLE
Smoothing of Density curve Data Driven Histogram

### ISSUE THREAD

**Issue by jricoiii** [isle-project/isle-editor#1277]
**Is your feature request related to a problem? Please describe.**
I think it might be nice to have an option to smooth out a density curve (at least to match the choose binwidth).  Of course one could go with one of the preset distributions.

**Describe the solution you'd like**
Would like an option to smooth density curve similar to ggplot's  geom_density

adjust | A multiplicate bandwidth adjustment. This makes it possible to adjust the bandwidth while still using the a bandwidth estimator. For example, adjust = 1/2 means use half of the default bandwidth.

**Describe alternatives you've considered**
Maybe before the data driven did adjust for binwidth (before it was number of bins)

**Additional context**
Notice how the density curve is not changing as number of bins changes
![image](https://user-images.githubusercontent.com/50716185/91513824-1bf6fb00-e89a-11ea-85d2-08ecad642ded.png)

![image](https://user-images.githubusercontent.com/50716185/91513784-01bd1d00-e89a-11ea-86ce-9ecba5d44942.png)

**Comment by Planeshifter** [comment]
This feature will land in the next editor version per the changes in d11af61feb749425ef6d290598526f003b5e8f64.

Thanks again for this suggestion!
