### ISSUE TITLE
Removing Filter Corrupting Data Frame

### ISSUE THREAD

**Issue by jricoiii** [isle-project/isle-editor#1278]
**Describe the bug**
When I create filters and then remove them, some of the other non-filtered variable get turned in NA (as viewed in Data Explorer)

**To Reproduce**
This is happening in my recently made lesson
https://isle.kymetis.com/ohlone_2020_collab/03_Numerical_Variables_Introduction_Aug26/
Page 4 - Data Explorer
Filter `AGEP` to any range (38-56)
Click Create Filtered Dataset
Filter `hours_worked_wk` to >40
Click Create Filtered Dataset
Click X to remove the first filter for `AGEP`
(Another BUG : note the bar for AGEP has not reset)
Click X to remove the `hours_worked_wk`
(It also happens if you reset all in one click)

Now look at other variables and you will see many variables have become NAs - it is sort of random and doesn't turn all observations to NA.  Also when making any tables only a small subset (the non-NAs_) are available for analysis.

You can do other filters, create, remove and different variables become NAs

Note: the ranges for `AGE_P` and `hours_worked_wk` has reset.

**Expected behavior**

**Screenshots**

After removing filters
![image](https://user-images.githubusercontent.com/50716185/91599038-79cb2780-e91a-11ea-8897-77ad2b4eb14f.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser; Chrome

**Additional context**

**Comment by Planeshifter** [comment]
This bug should be fixed via commit 622fd51ee8c9a27327fb50664ef5bec266748ff0, which will be part of the next editor release.
