### ISSUE TITLE
bug in provideFeedback?

### ISSUE THREAD

**Issue by sacole167** [isle-project/isle-editor#1283]
Sorry. Ignore/delete this comment.
Some questions seem to be giving feedback when provideFeedback is set to False:
<img width="1340" alt="Screen Shot 2020-08-31 at 1 58 04 PM" src="https://user-images.githubusercontent.com/69658229/91768252-34b12a80-eb92-11ea-9ddb-23cc9d28d955.png">

**Comment by Planeshifter** [comment]
Closing this issue. Using `provideFeedback` insetad of `feedback` solves the problem. The latter refers to the feedback buttons for students to indicate whether they understand the material or are confused about it.
