### ISSUE TITLE
Allow hyperlinks in question text

### ISSUE THREAD

**Issue by sacole167** [isle-project/isle-editor#1286]
It appears it is not possible to embed hyperlinks in question text. There might be all sorts of use-cases where instructors wish to do that.

**Comment by Planeshifter** [comment]
The are several ways to do this, we just have to not assign a string to the question attribute but HTML nodes:

Using HTML <a> tag:

```jsx
<FreeTextQuestion question={<span>Who started the <a href="http://wikipedia.org">Wikipedia</a></span>} solution="Jimmy Wales" />
```
Using Markdown:

```jsx
<FreeTextQuestion question={<span>Who started the [Wikipedia](http://wikipedia.org)</span>} solution="Jimmy Wales" />
```
