### ISSUE TITLE
Refresh Heart Disease in the ISLEDocs link

### ISSUE THREAD

**Issue by jspm-kymetis** [isle-project/isle-editor#1289]
**Describe the bug**
ReferenceError: heartdisease is not defined

**To Reproduce**
1. Go to https://isledocs.com/docs/data-explorer
3. Scroll down 

**Expected behavior**
Data Explorer

**Screenshots**
![image](https://user-images.githubusercontent.com/62388791/92054083-f23b4980-ed5b-11ea-8c26-305c75b144bb.png)

**Comment by Planeshifter** [comment]
The data explorer in next version documentation will render per commit d46ec8c6423f8aca04549e8cb9f58f455736acd5.
