### ISSUE TITLE
Unable to generate plots for filtered data frame

### ISSUE THREAD

**Issue by jricoiii** [isle-project/isle-editor#1292]
**Describe the bug**
I can make a histogram or bar chart with group by a particular categorical variable, but after I filter a the same categorical variable to fewer than it's original levels - nothing happens when clicking on Generate.
( exported today with newest ISLE editor)
https://isle.kymetis.com/ohlone_2020_collab/01_Intro_Data/

**To Reproduce**
filter a cat var to fewer levels
attempt to graph boxplot or histogram and group by the filtered level
generate - nothing happens

**Expected behavior**
graph is generated

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
You could get around this by not doing the filter, but often you will want to see a numerical variable across just 2 levels of a categorical (for example married vs unmarrried or Black vs White)

**Comment by Planeshifter** [comment]
Fixed by commits https://github.com/isle-project/isle-editor/compare/d25d8acee07a...204d62a95994 that make sure category labels are properly assembled for factor variables for which an ordering is supplied.
