### ISSUE TITLE
Contingency Table - Columns Total not correct (showing under wrong column)

### ISSUE THREAD

**Issue by jricoiii** [isle-project/isle-editor#1294]
**Describe the bug**
Making contingency table and getting error in column calculations? 
https://isle.kymetis.com/ohlone_2020_collab/01_Intro_Data_In_Class_Survey_Q/
(Using Page 6 Survey Data Explorer)

**To Reproduce**
Create contingency table .
Columns totals don't correspond with their proper column.

**Expected behavior**
totals equal sum of the column

**Screenshots**
![image](https://user-images.githubusercontent.com/50716185/92413770-7b5cd280-f106-11ea-93d8-7008cdfd26ea.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Planeshifter** [comment]
This bug is now fixed per commit https://github.com/isle-project/isle-editor/commit/d25d8acee07abeb450deda6fb4911a2ed88eda3d.
