### ISSUE TITLE
Multiple choice questions: allow distractor multiple answers

### ISSUE THREAD

**Issue by sacole167** [isle-project/isle-editor#1299]
The MultipleChoiceQuestion allows for multiple answers. But it does not allow the instructor to distract the student by saying "check all that apply" even when there is only one correct answer because ISLE does not allow for the (incorrect) selection of more than 1 answer.

It would be helpful to be able to allow the student to select more than one answer even if there only is one correct answer for either MultipleChoiceQuestion or SelectQuestion

**Comment by Planeshifter** [comment]
What you request should be possible by supplying the solution(s) as an array, see below examples:

Only one correct answer: 

```jsx
<MultipleChoiceQuestion
  solution={[ 1 ]}
  answers={[
    {content:"Incorrect", explanation:""},
    {content:"Correct", explanation:""},
    {content:"Incorrect", explanation:""},
    {content:"Incorrect", explanation:""}
  ]}
  question="Choose all that apply question with one correct answer"
/>
```

Multiple correct answers:

```jsx
<MultipleChoiceQuestion
  solution={[ 1, 2 ]}
  answers={[
    {content:"Incorrect", explanation:""},
    {content:"Correct", explanation:""},
    {content:"Correct", explanation:""},
    {content:"Incorrect", explanation:""}
  ]}
  question="Choose all that apply question with two correct answers"
/>
```

**Comment by sacole167** [comment]
Thank you. That works.

**Comment by Planeshifter** [comment]
Great! Closing.
