### ISSUE TITLE
Binning - Last Field is Greater than or Equal - but symbol is only Greater Than

### ISSUE THREAD

**Issue by jricoiii** [isle-project/isle-editor#1310]
**Describe the bug**
symbol is >  when should be greater or equal

**To Reproduce**
Bin a numerical variable

**Expected behavior**
symbol should be consistent with procedure

**Screenshots**
![image](https://user-images.githubusercontent.com/50716185/93146865-c8abe780-f6a4-11ea-941e-af0a219496a7.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Planeshifter** [comment]
Thanks for reporting this!
Fixed in commit 97c97ad905c1a7b3abfd9ac4eb20f7b4b48db856.
