### ISSUE TITLE
Option to Create a frequency table with counts and relative frequency

### ISSUE THREAD

**Issue by jricoiii** [isle-project/isle-editor#1311]
**Is your feature request related to a problem? Please describe.**
Could you add a check box to Frequency Table - for Counts (although I know this is the default table)

**Describe the solution you'd like**
I just want my students to develop a more critical eye - and seeing counts along with percents will help

**Describe alternatives you've considered**
create 2 back-to-back tables of counts then relative frequency

**Additional context**
![image](https://user-images.githubusercontent.com/50716185/93147344-cac27600-f6a5-11ea-871e-848aa4dfe3fe.png)

**Comment by Planeshifter** [comment]
Thanks for the suggestion! 
We could have two radio buttons, one for counts and one for relative frequencies, of which only one can be selected.
An alternative would be to allow for a frequency table showing both counts and relative frequencies, e.g. showing relative frequencies in parentheses in case both options are checked. Any thoughts on this?

**Comment by jricoiii** [comment]
I like the alternative option, since I want my students to always get counts and percents.

**Comment by Planeshifter** [comment]
Feature will land in next release per commit 666cf2745ab722d00e859f9825844317531f2221.

**Comment by gweinberg** [comment]
This is a good suggestion.

In general, tables should be allowed to contain multiple items, and the table tool should have various (radio buttons?  pulldowns with multiple selectability?).

If table cells contain multiple objects, then somewhere near the rendered table, it should alert/remind the user what object is what; akin to how Minitab does it, which is like "in each cell, top value is joint percentage; cell count appears below percentage; chi square contribution appears below cell count" etc.  For coding/rendering purposes, just have it stack different notifications on new lines above the table, one for each item that appears in the cells, e.g.,:

In each cell, top value is joint percentage.
Cell count appears below joint percentage.
Chi square contribution appears below cell count.
.
.
.

On each line of the printed description, you need to store the name of the item from the previous line.
If only one item per cell is enabled, remove the word "top" from the line.  

I guess marginals should also mimick the same info being shown in the cells (excepting things like chi square contributions of course).

**Comment by Planeshifter** [comment]
Closing this issue so that the changelog correctly picks up that the original proposal was implemented. I created a new issue to keep track of discussion and progress on Gordon Weinberg's latest suggestions on cell legends / descriptions.
