### ISSUE TITLE
Allow re-submissions for numeric questions

### ISSUE THREAD

**Issue by Planeshifter** [isle-project/isle-editor#1321]
**Is your feature request related to a problem? Please describe.**

Students would like the ability to re-submit answers for numeric questions, as it feels frustrating to be stuck with an incorrect response.

**Describe the solution you'd like**

Adding an option to number and related questions to allow for re-submissions even once the answer has been revealed. This is not always desired (e.g., when grading responses for correctness) but should be an option.

**Comment by gweinberg** [comment]
And when the students download the pdf of their answers, they should get the full list of answers they submitted (if they don't already), tagged as something like, "first submission, second submission,..."; or maybe even, when they press "submit/download pdf" it should give students the option to "show only my most recent answer for each question"  "show all old answers for every question" or something like that.

**Comment by gweinberg** [comment]
That's a fair point about the download being lengthy if we include all prior versions of open-ended answers.  Not sure what the right balance is.

I'd suspect it could be more interesting, however, for users to see their prior attempts of open ended answers in general than prior attempts of single-number answers.

**Comment by Planeshifter** [comment]
Added a new checkbox to the lesson submit notification, which will only show up in case the user has submitted at least one question multiple times:

![image](https://user-images.githubusercontent.com/1913638/127947300-b3ed9ba3-3367-40c0-99bd-3227e98b0388.png)

When downloading a version of the report with all submissions, they are printed like this:

![image](https://user-images.githubusercontent.com/1913638/127947492-41d07f89-3c30-4c93-9b35-16286ae2a974.png)

(note: changed the behavior after taking the screenshot to start the numbering at `1`)

However, the default is for the checkbox to be ticked to preserve the current behavior of only including the latest submission.

**Comment by Planeshifter** [comment]
Closing this issue since the original feature has meanwhile been realized via the `submitAfterFeedback` property of the `<NumberQuestion />`, which allows re-submissions for incorrect answers after the solution has been revealed. One may also use the `nTries` property to choose a number of tries that students have before being shown the correct solution.
