### ISSUE TITLE
buttons in lower left overlap text

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#1322]
Currently, the stack of buttons in the lower-left of an ISLE lesson (for calculator/sketchpad/etc) overlap any text; e.g., see screenshot:

![image](https://user-images.githubusercontent.com/31780210/93403206-d7390100-f854-11ea-986a-6883b17f7bb6.png)

(I know they're semi-transparent but it's still difficult to read through them).

Either there should be default borders on ISLE lessons so that background text doesn't extend behind the buttons, or else they should maybe slide in and out upon mouseover.

[Edited to add]:
I see that it depends on the user's broswer font / resolution size (I've got my browser font size at 16 pt; so in the editor it looks fine [I guess editor uses 12 pt default] but then in my browser the buttons overlap the text.)

**Comment by Planeshifter** [comment]
Refactored the toolbar to be horizontally laid out:

![image](https://user-images.githubusercontent.com/1913638/93640590-d7f2a400-f9c8-11ea-8044-18539ee51d75.png)

Also have a new button to the left to collapse or reveal the toolbar:

![image](https://user-images.githubusercontent.com/1913638/93640654-f193eb80-f9c8-11ea-8130-0a400dbade52.png)

**Comment by gweinberg** [comment]
nice!
