### ISSUE TITLE
request force light background when clicking images

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#1324]
When you click an image in an ISLE lesson you get an image control window (where you can zoom in, zoom out, copy, etc).

But, at least on my broswer (Firefox, on Win10), the default background is dark grey:

![image](https://user-images.githubusercontent.com/31780210/93721457-76643e00-fb5e-11ea-80ab-9a5d36150ff2.png)

For images that are transparent, this makes dark text unreadable, hence users can't use this to view an enlarged version of the plot.

Request to force background color on these windows that are the same background color as the ISLE lesson the image came from.  [Or else maybe just white.]

**Comment by Planeshifter** [comment]
Thanks for filing this issue!

We now have a white background color per 4a3e4cd57572549c84acec0f36ffc4ae4a99241a.

**Comment by gweinberg** [comment]
Cool.

That likely takes care of 95% of use cases, but now if an instructor makes a transparent image with white text?  (Suppose the lesson had a dark background color, like it was a coding lesson in "night mode" or something).   Now in those cases it won't be seen again upon popup.

How about a new toggle on the image popup window, a "toggle background color" or "choose background color"?

**Comment by Planeshifter** [comment]
Fair point. Feel free to create an issue; to take care of this special case a toggle might be the best option as we cannot easily pick up the background color of the image in the main lesson. For example, just using the main background color of the lesson won't be sufficient as the image might be placed inside a container, say a `<Panel />` component, with a different manually specified background color.

**Comment by gweinberg** [comment]
yep I was thinking about that exact issue, you'd need some AI that could detect the actual color behind the transparent image!
