### ISSUE TITLE
Error 413

### ISSUE THREAD

**Issue by sacole167** [isle-project/isle-editor#1335]
I have a few files that I am trying to upload to Owner files that are apparently too large and giving me error 413. The files are in the 30-70 MB range. Is there anything that can be done about that?

**Comment by Planeshifter** [comment]
There is currently a 30mb hard-coded limit to the size of files that can be uploaded. May I ask what kind of file you are trying to upload?
For example, files such as videos we would suggest to host on YouTube or some other video platform.

**Comment by sacole167** [comment]
These are fingerprint images from a fingerprint proficiency test. I could possibly host them on Google Drive?

**Comment by Planeshifter** [comment]
Embedding files hosted on Google Drive proved complicated in the past. If you create a GitHub repository (public or private, either way will work) and upload them there, you can copy the link to the raw file and embed it into your lessons. 
Maybe you can give that a short first? 
Alternatively, I will look into adjusting the size limit while being cognizant of the fact that the dashboard's upload functionality is not really geared towards large files right now (e.g., no progress indicator) and our server's limited disk space.

**Comment by sacole167** [comment]
I resolved by changing the file to JPEG and uploading to owner files. Linking to files in a private repository in GitHub did not work for some reason.

**Comment by Planeshifter** [comment]
Closing this out for now.
