### ISSUE TITLE
Overlay histogram - counts vs density

### ISSUE THREAD

**Issue by jricoiii** [isle-project/isle-editor#1338]
**Is your feature request related to a problem? Please describe.**
Maybe it is just me - but it seems like if you are comparing histogram - you don't really want to look at counts ( can be misleading), you'd rather see (percent) density.  Currently you can't see density without getting a overlay density line.

**Describe the solution you'd like**
Would like to toggle between density (percents) or counts.

**Describe alternatives you've considered**

**Additional context**
Take a look for yourself

AGE distribution from 2 cities - two cities are Fremont (00109) and Sunnyvale (08502)
![image](https://user-images.githubusercontent.com/50716185/94197674-f47c5980-fe6a-11ea-9fa8-80eb5232e3a6.png)

![image](https://user-images.githubusercontent.com/50716185/94197597-db73a880-fe6a-11ea-8caa-ac6e11d99fd9.png)
( the line is distracting?)

**Comment by Planeshifter** [comment]
Definitely can see a benefit to plot densities without the line, thanks for bringing this up! In the interim, clicking on the lines in the legend will toggle the lines on and off, so you can already generate the plot you would like, albeit requiring extra steps.

**Comment by Planeshifter** [comment]
The histogram options have been refactored to allow for just displaying the density values without overlaying any fitted distribution. This feature will land in the next release.
