### ISSUE TITLE
Enable incomplete answers in SelectQuestionMatrix

### ISSUE THREAD

**Issue by sacole167** [isle-project/isle-editor#1339]
"Submit" is greyed out in SelectQuestionMatrix unless a selection is made in each cell. It would be nice to have a toggle function that would allow one to accept incomplete answers.

For example, I have a very long exercise that use the SelectQuestionMatrix. I don't know whether the students will be able to complete the entire matrix, but I want them to complete as much as they can.

For now I am using the workaround of having an answer options "incomplete."

**Comment by Planeshifter** [comment]
The next version of the editor adds a boolean `allowIncomplete` flag to the SelectQuestionMatrix, which when enabled will allow students to submit without making a choice for every cell. There are other changes made to the SelectQuestionMatrix such as the addition of an `nTries` attribute and improved feedback in case of wrong responses.
