### ISSUE TITLE
faceted histogram axis labels overlap graphs below

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#1350]
When making faceted histograms, they are currently rendering with not enough whitespace between the rows of plots; the plots on subsequent rows are therefore overlapping the x axis labels of the rows above; for instance, the red plot on the right is overlapping the x axis label from the plot above it:

![paneled-histogram-title-bug](https://user-images.githubusercontent.com/31780210/94685221-19534f80-02f7-11eb-8ad0-8ee41f0e3d0e.png)

There needs to be added whitespace padding above and below each row; and/or the plot needs to be re-defined so that the "bottom" of the previous row is taken to be just below the previous row's *label* (currently it looks like it's taking the previous *axis* plus a little bit of padding to be the "bottom" of the previous row).

**Comment by Planeshifter** [comment]
We now manually adjust the height of the plot in case of a facetted plot per becf7372215226ad5caf3060d6812e0ad5db9d4f.
