### ISSUE TITLE
box plot; factors lose order when a second group by variable is added

### ISSUE THREAD

**Issue by jricoiii** [isle-project/isle-editor#1369]
**Describe the bug**
When creating boxplots across 2 variables, the ordering gets corrupted.

**To Reproduce**
Just use a second group by variable (I noticed this also happens with recently bin quant variables too.)
Can't show right now , since explorer has bug that won't allow binning...(entire page/lesson goes blank)

**Expected behavior**
would expect order to remain.

**Screenshots**
![newplot (74)](https://user-images.githubusercontent.com/50716185/95378484-d6feb500-0898-11eb-9ca4-231e30c75791.png)
![newplot (75)](https://user-images.githubusercontent.com/50716185/95378527-e4b43a80-0898-11eb-94e5-05aa60d8c653.png)

**Link to ISLE lesson**
https://isle.kymetis.com/RicoStatsF2020-09/ACS_Data_Explorer/

```jsx

```

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Planeshifter** [comment]
Thank you very much for reporting this bug! 
A fix is included in 71084c067dcff31902d17723d6d88f2e77059cae.
