### ISSUE TITLE
Allow entry of fractions in NumberInput

### ISSUE THREAD

**Issue by sacole167** [isle-project/isle-editor#1398]
It would be helpful to enable the input of values as fractions (e.g., "2/3") into NumberInput in the same way it possible for NumberQuestion.

This would be helpful for teaching students to construct likelihood ratios which are more easily conceptualized as fractions.

**Comment by Planeshifter** [comment]
This is possible by setting the `numbersOnly` property to `false`.

See below for a code snippet:

```
<Panel>

    <NumberInput
        legend="Not accepting fractions"
        defaultValue={0}
        step="any" numbersOnly={true}
    />
    
    <NumberInput
        legend="Accepting fractions"
        defaultValue={0}
        step="any" numbersOnly={false}
    />

</Panel>
```

which is hosted at https://isle.stat.cmu.edu/demonstrations/number-input-fractions

**Comment by sacole167** [comment]
That works. Thank you. This is just cosmetic, it doesn't bother me, but you might want to know:

When you enter a fraction, Latex first renders the numerator of the fraction as the string:

<img width="1516" alt="Screen Shot 2020-12-04 at 5 17 11 PM" src="https://user-images.githubusercontent.com/69658229/101229422-07728d80-3655-11eb-979a-69c826e23477.png">

Then, when you tab out of the NumberInput box, Latex renders the full fraction as a decimal:

<img width="1516" alt="Screen Shot 2020-12-04 at 5 17 25 PM" src="https://user-images.githubusercontent.com/69658229/101229439-21ac6b80-3655-11eb-8647-cf9b61113d5d.png">

**Comment by Planeshifter** [comment]
Yes, I think it would be a good idea to preserve the rendering as a fraction. Will look into it!
