### ISSUE TITLE
ISLE Crashing when Test - Two Sample Proportion Test

### ISSUE THREAD

**Issue by jricoiii** [isle-project/isle-editor#1402]
**Describe the bug**
Using 2 sample prop test - I am getting ISLE to crash when grouping by a filtered categorical variable to only 2 levels.

**To Reproduce**
I filtered age 30-40, sex to men and PUMA to 00108 and 00109. Then collapsed Educ to Binary 0 less BA and 1 BA or more

ran 2sampleproptest , var=new_BA_cat , groups: PUMA

hit calculate 

ISLE crashes  ( I played around with it and only could get it to crash on PUMA / it did not crash on Sex as Group)

**Expected behavior**
not crashing

**Screenshots**

Prior to crash
![image](https://user-images.githubusercontent.com/50716185/96352685-f99f8380-1079-11eb-9073-cad367873ff9.png)

**Link to ISLE lesson**
https://isle.kymetis.com/ohlone_2020_collab/06_Sampling_Oct_16/

**ISLE Code**
If applicable, paste the code of the problematic component below:

```jsx

```

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jricoiii** [comment]
also go to crash by 2 sample 
workclass = govn
group = sex

**Comment by jricoiii** [comment]
actually its crashing even for single sample
var = collapsed categorical  education (BA+ or <BA)

**Comment by jricoiii** [comment]
this one worked
![image](https://user-images.githubusercontent.com/50716185/96353212-d9be8e80-107e-11eb-8bbe-9670dc89d9e5.png)

don't know what's happening...

**Comment by Planeshifter** [comment]
This issue is now fixed per 9058cb74aec841755a7a210b447763099d1bfb09.
