### ISSUE TITLE
chi-square info in contingency table

### ISSUE THREAD

**Issue by abbyflynt** [isle-project/isle-editor#1472]
Would it be possible to either have the chi-square test output a table with observed counts, expected counts, and contributions to the chi-square test statistic, and/or in the already existing contingency table, allow options to include the expected counts and contributions?

Thanks!

**Comment by gweinberg** [comment]
and also the ability to run the chi square test by entering the cell values, without needing an actual dataset.  Maybe, some kind of matric/table widget, where you can specify the number of rows and columns, and then enter the cell values?  [this should probably be a new request, although requested unified ability to run various tests with only summary values is probably on the burner already]

**Comment by Planeshifter** [comment]
Chi-square test output now includes a table with observed counts, expected counts, and contributions to the chi-square test statistic. Closing this issue for tracking purposes and release notes; request to allow running tests without data is not forgotten.
