### ISSUE TITLE
Bar Chart Issues - Relative Frequencies broken?

### ISSUE THREAD

**Issue by jricoiii** [isle-project/isle-editor#1474]
**Describe the bug**
Bar Chart not working, seems like the relative frequencies inside each group is just not working.

**To Reproduce**
combined levels in a categorical variable
used that as main variable for bar chart, group by another categorical
clicked on relative, stack

**Expected behavior**
a proper stacked bar chart with all bar out of 100%

**Screenshots**
![image](https://user-images.githubusercontent.com/50716185/99136247-bb45a780-25d8-11eb-94b4-ff75aa119984.png)

**Link to ISLE lesson**
https://isle.kymetis.com/ohlone_2020_collab/10_Chi-square_Test_Nov11/

**ISLE Code**
If applicable, paste the code of the problematic component below:

```jsx

```

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jricoiii** [comment]
![image](https://user-images.githubusercontent.com/50716185/99136599-c3064b80-25da-11eb-92fa-df31a0e7cda4.png)

**Comment by jricoiii** [comment]
put into google sheets

**Comment by Planeshifter** [comment]
Can reproduce, investigating now.

**Comment by Planeshifter** [comment]
Problem is now fixed, will be releasing a new editor version out tonight. Please try a hard refresh of https://isle.kymetis.com/ohlone_2020_collab/10_Chi-square_Test_Nov11/ to verify that the barchart behavior is restored.

Thanks for filing this issue!
