### ISSUE TITLE
request "visibility setting" on Upload Lesson in Editor

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#1478]
Currently, when using the Editor to upload/post a lesson to an active ISLE course, the lesson posts as "visible" to students.  There is no indication of this, and no toggle to change this behavior.

Often, we are developing and deploying the lesson several days in advance and need to test out / debug before wanting to make visible and we therefore need to remember to go online and click to hide/unpublish the lesson.

Regardless, the editor should give a clear indication and some toggle control.

Therefore, request for an additional toggle on the Upload Lesson panel, something like this:

![image](https://user-images.githubusercontent.com/31780210/99319127-00671500-2837-11eb-9ff8-bf0c4c53feea.png)

(Maybe having two separate check boxes isn't the best for the intended functionality, since it couldn't be possible to have them both on, or both off; but you get the idea)

**Comment by Planeshifter** [comment]
This functionality will be available starting with the next editor release. Thanks for the suggestion!

**Comment by gweinberg** [comment]
thanks for the new functionality.  One question and one issue:

Question:  I'm not sure I understand the difference between "show in gallery" versus "release to students."  If shown in gallery but not released, does that mean students could see it but not open it?  This would be a new functionality right?

Issue:  The panel is now so long it's going behind the windows toolbar on my desktop:
![image](https://user-images.githubusercontent.com/31780210/101270157-67942d00-3744-11eb-8314-654f4fa6c0b5.png)

**Comment by Planeshifter** [comment]
Next version of the editor will have an updated layout that should not exceed the bottom of your desktop.

Concerning the gallery, yes, showing them in the gallery makes lessons available to other _instructors_ on the dashboard.
