### ISSUE TITLE
1 lesson only is unresponsive

### ISSUE THREAD

**Issue by sacole167** [isle-project/isle-editor#1504]
ISLE 0.71.6 is not posted on the [install page](https://isledocs.com/docs/overview/install).

The Shoeprint Marking lesson ONLY is unresponsive. Cannot scroll, cannot type. Can't close the window, but you can minimize and go to full screen. Can't quit.

I wonder if this is because it got stuck and I had to Force Quit trying to download 0.71.6. See screenshot:
<img width="1218" alt="Screen Shot 2020-11-24 at 11 12 09 AM" src="https://user-images.githubusercontent.com/69658229/100140700-2ba8c000-2e46-11eb-9f18-8130136361f4.png">
The Calculating LRs lesson works fine:
<img width="1112" alt="Screen Shot 2020-11-24 at 11 14 28 AM" src="https://user-images.githubusercontent.com/69658229/100140760-3d8a6300-2e46-11eb-9c0b-d9ad835079ef.png">

I am still not able to update directly from within ISLE. Never have been.

**Comment by Planeshifter** [comment]
-   The isledocs.com page has been updated to display the download link to the latest editor
-   I am able to reproduce the issue of the lesson breaking the editor and am looking into this now; hopefully there will be a fix shortly (i.e., by tomorrow)

**Comment by Planeshifter** [comment]
Closing as the issue has been fixed. A patch will be included in the next editor release.
