### ISSUE TITLE
request ability to show navigation at both top and bottom of questions panel

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#1538]
When a series of questions is in "Pages" format, the navigation tool appears only at the top of the panel, not also the bottom.

When a series of questions is in "Slider" format, the navigation tool appears only at the bottom of the panel, not also the top.

It is not uncommon for a panel of questions to be taller than a browser window, in which case, regardless of which format ("Pages" or "Slider"), the student may fail to realize they need to navigate to the next panel.

This is especially problematic when the question panel is at the bottom of an assignment which includes a "finish assignment" button, since the student, failing to realize they needed to navigate to the next panel, may therefore click "finish assignment" and miss several more panels of questions.

Therefore, request for editor functionality allowing the navigation tools to be put at both the top **and** the bottom of the panel:

![image](https://user-images.githubusercontent.com/31780210/101417056-15c0e380-38b9-11eb-931a-e78e39fd1b40.png)

(It's possible this already exists and I merely don't know about it)

**Comment by Planeshifter** [comment]
For the `<Pages />` component, this does already exist by setting the `paginationBelow` attribute, e.g.

```
<Pages paginationBelow >

<!-- content comes here -->

</Pages>
```

Let's leave this issue open though since I can definitely see this functionality being also useful for the slider component.

**Comment by gweinberg** [comment]
Oh. but can it do *both* in the same panel, so that it shows pagination at the top *and* the bottom?

**Comment by Planeshifter** [comment]
Yeah, that's what it's currently doing. No way for `<Pages />` to only show the pagination on the bottom. Should we support all three options?

Option would be to do something like `<Pages pagination="both"`, `<Pages pagination="top"`, and `<Pages pagination="bottom"`.

**Comment by gweinberg** [comment]
All three options would be good!
And also for <Slider>

**Comment by Planeshifter** [comment]
The next release will contain a `pagination` property for both `<Pages />` and `<Slider />` allowing fine-grained control on whether to display pagination buttons at the `top`, `bottom`, or `both`. Closing...
