### ISSUE TITLE
request: report editor should default to "save as" (i.e., default asking to re-name the file)

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#1592]
Currently (at least in Firefox on Win10), in the Report Editor, neither "Save HTML" nor "Export PDF" allow the user to re-name when saving.  It seems like it simply names the file whatever the corresponding Data Explorer had been named internally.

It's common for students to save different working versions as they work on, say, a week-long project.  If the file is default named the same thing, it's possible to unintentionally lose old versions if the new version overwrites.  The user should be able to re-name upon save.  Additionally (even if the OS asks/warns that an existing file with that name already exists), it would also be nice for the user to be able to more descriptively name the file upon download.  Finally, it would be nice from instructor standpoint if the platform allowed/encouraged students to easily rename files with their name (so that we don't see 200 files with the same name).

So I think the "Save HTML" and "Export PDF" functionalities to default to a "save as..." instead of "save", automatically giving a dialog that asks what the file should be named.

**Comment by Planeshifter** [comment]
After digging a bit into this, it looks like this is standard behavior on Mozilla Firefox that cannot be overwritten / customized by any web application. You may try downloading files from other web apps such as Google Docs and should observe the same behavior. Other browsers such as Chrome, Edge, or Brave let one change the filename when saving the file.

On Firefox, changing one's preferences to "always ask you where to save files" under the "Files and Applications" section will prompt one to select the download location and also allows one to change the filename when saving a file:

![image](https://user-images.githubusercontent.com/1913638/103391268-8f2da980-4ae6-11eb-9571-7d9de5074167.png)

**Comment by gweinberg** [comment]
I already have that setting enabled in Firefox, so it's something else.
[Unfortunately we can't test it further until we get ISLE working on my Firefox again]

**Comment by Planeshifter** [comment]
Issue has meanwhile been resolved. Anyone who encounters the issue of not being able to choose a custom file name when downloading a file should check their browser settings (all major browsers have a checkbox option akin to the one above so that they always ask for where to save the downloaded file and under what name). For users who have their browsers configured to not ask for a name, we now append an incrementing version counter to the filename to avoid repeatedly saving under the same file name.
