### ISSUE TITLE
explanation text cut off by right edge of editor window

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#1661]
This may have already been submitted (not by me though?).  But, at least in the editor, explanation popup text is cut off by the right edge of the window:

![image](https://user-images.githubusercontent.com/31780210/106342514-2d8c6680-626f-11eb-9f52-25da8bf1ca06.png)

**Comment by Planeshifter** [comment]
The popup explanation will now automatically be positioned without forcing it to be placed to the right, which will fix the popover getting cut off when there is not enough screen estate available.
