### ISSUE TITLE
bottom of "select component" menu gets cut off when searching

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#1662]
Editor version 0.74.3, on Windows10.

Right click in editor to pull up the "Select Component to Insert" menu -->
plant cursor in the "Search for component" window at the bottom of the popup -->
start typing anything in the search window.

Then the menu expands and the bottom of the menu (including the search window) gets cut off by the bottom of the editor:

![image](https://user-images.githubusercontent.com/31780210/106370696-87059b80-632a-11eb-8d73-9347730ed274.png)

This feels like the same sort of bug as issue #1661, i.e., various popups don't properly adjust for the edges of the editor.

**Comment by Planeshifter** [comment]
Thanks for filing this issue!

Starting with the next release of the editor, a scrollbar will appear if a maximum amount of the available height is exceeded when searching for components:

![image](https://user-images.githubusercontent.com/1913638/106371303-dfd83280-6330-11eb-9ac1-ef248d06c096.png)
