### ISSUE TITLE
in report editor, underline doesn't get new text color (but in pdf it does)

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#1673]
Playing around with font choices in the report editor, I discovered a minor functionality quirk:

make text -> change font color -> then select and underline text;

or equivalently:

make text -> select and underline ->  then select and change font color.

(For instance, try it with orange font color).

The expected behavior would be for the underline color to match the font color.

However, in the on-screen report editor, the underline doesn't get the new font color (the underline looks blue or black); but in the rendered pdf, the underline does have the text color as would be expected.

**Comment by Planeshifter** [comment]
This issue is now fixed per 7cc5e1ac06a64a8c40bc2856cd6b39287f61f259.
