### ISSUE TITLE
return of editor bug: top bar disappears and space appears at bottom, when running output in preview

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#1700]
Looks like an old bug has returned:  In the editor, when executing output in the preview pane, the bar at the top of the editor (with the refresh etc commands) disappears, and a blank space appears at the bottom of the editor window:

![image](https://user-images.githubusercontent.com/31780210/107288044-d5a0ed00-6a30-11eb-8ec7-43631c5eca64.png)

I think I made a boxplot before it happened. 

Follow up:  It's being initiated by what I seem to recall was the cause the last time we experienced this:  In the editor, when using the toolbox in the preview window, in cases where a menu in the toolbox would, I think, go below the bottom of the editor window, I think that's what's causing the bug.   [For instance:  Editor -> scroll the window so that the "toolbox" button is relatively near the bottom of the editor -> toolbox -> select anything in the toolbox that has a relatively tall dialog box.

**Comment by Planeshifter** [comment]
Yes, was able to reproduce, thanks for the detailed description; it happened when the options of a select box exceeded the available vertical space. Adjusted the behavior such that the error should not occur going forward.
