### ISSUE TITLE
autopopup is sometimes blank

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#1701]
In the editor, the context dependent auto-popup that occurs while typing (which, by the way, can be very distracting and we should have a toggle to disable it), is occassionally blank; e.g.:

![image](https://user-images.githubusercontent.com/31780210/107295750-076c8080-6a3e-11eb-8aca-54d6a192674b.png)

I've discovered that you can make it go away by creating another popup and then making that one go away (which I typically do by clicking on the background of the editor).

**Comment by Planeshifter** [comment]
I believe that this issue should not occur anymore in the next release. Would be good to get your confirmation once the new editor is out at the end of the week.

**Comment by gweinberg** [comment]
I'll let you know!

**Comment by gweinberg** [comment]
Just for some recent follow up, I haven't seen this bug in recent versions of the editor.

**Comment by Planeshifter** [comment]
Thanks for the follow-up! I have not encountered the issue myself for a while, too. Closing this issue for now. We can re-open the issue should the bug re-appear.
