### ISSUE TITLE
"select submission to view" jumps back to top upon re-opening

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#2008]
On the report editor,  in Instructor mode, after selecting a submission to view, and then upon going back to the "select submission to view" menu, the expected behavior would be that the menu would already be scrolled to the location of the ID of the project that had been previously shown, and that project ID should be selected.

However, (on Win10, Firefox 88.0.1), the menu is scrolled all the way to the top each time, and the top project in the list is the one that is selected.

![image](https://user-images.githubusercontent.com/31780210/117912595-c3438300-b2ad-11eb-8b8b-26fdb95356d7.png)

Request to change to the expected behavior.

**Comment by Planeshifter** [comment]
Behavior has been changed such that starting with next editor, it will be ensured that dropdown menu will be opened in the previous scroll position. Thanks for bringing this to my attention!
