### ISSUE TITLE
toolbox doesn't appear in editor

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#2034]
I don't remember if this has been discussed previously.  When editing a data explorer (editor Version 0.75.7, although I now recall this was happening on older versions as well), nothing happens when clicking "Show Toolbox" in the rendered pane.

[This is on Windows]

More info:
It seems to happen randomly/intermittently; for instance, I was just editing reasoning-with-data\summer1_2021\lab02, and in the *first* data explorer on the lesson, "show toolbox" made the toolbox appear in the editor but not on the *second* data explorer on the lesson; then I "exported" the lesson, and returned to the editor, and then on *neither* data explorer did "show toolbox" do anything.  For the most part, it seems like "show toolbox" doesn't work in the editor.

**Comment by Planeshifter** [comment]
This should now be resolved per commit 674c7b6dbb201f79f6cf0df1e99c45e046f5a66f.
