### ISSUE TITLE
diagonal line on qqplot wrong or missing with transformed data

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#2067]
Go to:

https://isle.stat.cmu.edu/36-200-first-summer-21/lab3/

1) example of qq diagonal going the wrong way:

transform -> "transformation, functions" -> create new variable called "log-GDP-per-capita" by: ln(GDPPerCapita)

then:

models -> simple linear regression -> Y=log-GDP-per-capita, X=internet [remark for Philipp, this reverses the roles of the variables from the exercise in the lab] -> omit missing values -> generate

which yields regression output which, when clicking the "model diagnostics" button, gives the following qqplot, on which the orange diagonal is running the wrong way:

![image](https://user-images.githubusercontent.com/31780210/120215408-b0183900-c203-11eb-9fa4-08a68d95d7cc.png)

[The regression output otherwise seems to still be correct though, as compared with Minitab.]

Same thing happens if you try Y=sqrt(GDPPerCapita), and X=Internet:

![image](https://user-images.githubusercontent.com/31780210/120219784-c1fcda80-c209-11eb-8ef0-d35d8570def5.png)

With these particular variables, the bug seems to only happen if the transformed variable is on Y; so for instance, the bug doesn't happen if you try SLR with the tranformed variable on X, e.g;

![image](https://user-images.githubusercontent.com/31780210/120220097-3b94c880-c20a-11eb-87cb-b6cf8d0cf93b.png)

it also doesn't happen if you use the *untransformed* variables.

2) examples of qq diagonal missing:

Same web link -> 

transform -> "transformation, functions" -> create new variable called "log-revenue" by: ln(TaxRevenue)

then:

models -> simple linear regression -> then use **log-revenue** for one of the variables (doesn't matter which), and use **Internet** for the other variable -> omit missing values -> generate

Then, regardless of which variable was Y, you get regression output which, when clicking the "model diagnostics" button, gives a qqplot on which the orange diagonal is missing.

Here's the resulting qqplot if you used log-revenue on X (and Internet on Y):
![image](https://user-images.githubusercontent.com/31780210/120216433-0174f800-c205-11eb-9cc0-1f324a4b3c91.png)

Here's the resulting qqplot if you used log-revenue on Y (and Internet on X):
![image](https://user-images.githubusercontent.com/31780210/120220690-253b3c80-c20b-11eb-9f29-288f16678b5c.png)

Either way, the orange diagonal is missing.

Trying SLR with the *untransformed* variables Internet and TaxRevenue seems to yield a qqplot that looks correct.

**Comment by Planeshifter** [comment]
Thanks for filing this issue, which should be fixed in the next editor version per commit 5286761cbe3820a51b78b8eb1be860710a62e6a0: It looks like `NaN` / missing values were not handled correctly in the QQ-Plot. We can re-open the issue in case the problem re-surfaces / hasn't been completely resolved, but on my end I am now getting the expected results.
