### ISSUE TITLE
legend of labeled scatterplot doesn't show up until full-screen

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#2068]
The particular variables or particular lesson might not matter, but just for instance, go to: 

https://isle.stat.cmu.edu/36-200-first-summer-21/lab3/ ->

toobox -> plots -> scatterplot -> x-axis = "GDPPerCapita", y=axis="Internet" -> color by "majority rural" -> split by "majority rural" -> linear -> generate.

The plot legend isn't showing up on the plot in the output panel upon generating, I have to toggle full-screen and then toggle back out of full screen to get the legend to show up on the plot in the output panel.  

Here's what my output panel looks like immediately upon generating:

![image](https://user-images.githubusercontent.com/31780210/120244295-dc4dad00-c237-11eb-9978-c5e1968deda4.png)

If I toggle to full screen, the legend shows up in full screen mode, then if I toggle back out of full-screen, *only then* does the legend persist:

![image](https://user-images.githubusercontent.com/31780210/120244499-5b42e580-c238-11eb-9e1e-d32f41e21944.png)

**Comment by Planeshifter** [comment]
Thanks for reporting this bug, which was also separately brought to my attention!
 
Just pushed changes in commit 44873af9d6762e8b3a1a2cafc0ce6a5402cdca28 should have this issue vanish with the next editor update.
