### ISSUE TITLE
[bug] vertical scale on just one histogram of panel

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#2088]
Go to:  https://isle.stat.cmu.edu/36-200-first-summer-21/forestfires_project1/ ->

histogram -> of "area" -> grouped by "month" -> mode = "facets" -> columns = "6" -> generate.

Then, on all the plots except one of them, the vertical scale is in whole numbers which are shown to the nearest whole number, or decimals like "0.5" which are shown to the nearest tenth.

But on the upper-left plot, everything on the vertical is given to the third decimal place.  (E.g., instead of frequency 2, it gives "2.000"; instead of frequency 0.5, it gives "0.500"; etc):

![image](https://user-images.githubusercontent.com/31780210/121265648-1e559f00-c887-11eb-94bb-d9f9c54e8912.png)

Also, it looks like just for that upper-left plot, it's chosen too many tickmarks.  Based on what appears to be the internal routine for the other verticals, I think it should probably be labeling just "0", "1", and "2" for that upper-left.  [For instance, for the plots that only go up to 1, it only ends up labelling "0", "0.5", and "1".]  In fact, I'm wondering whether part of the bug might be something like, for the upper-left plot, for some reason it's choosing to make five vertical tickmarks only because that's the max number of vertical tickmarks on one of the other plots in the series, instead of making a reasonable choice for each plot separately?

**Comment by Planeshifter** [comment]
Thanks much for reporting this! Will be fixed in upcoming editor release so that the top-left plot won't have tick mark labels rounded to the third decimal place.
