### ISSUE TITLE
[bug]: In Answers->Show Extended, scrolling goes haywire

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#2090]
On Win10, Firefox89, 120% resolution, fontsize=16, as an instructor -> click to show "answers" for a question -> "show extended".

Then, the scrolling functionality in the "show extended" panel goes haywire, I can't scroll and have the scrolling stop at a given place, it keeps jumping around.  See video:

https://cmu.zoom.us/rec/share/48UCEbVfE4updvspPpxjwmwiAioo5nWKKeGfrj1K7NRjeekJlwHk_eCJIB2g0weD.TTiVKqzPm2rIdqv2

**Comment by Planeshifter** [comment]
Thanks for reporting this problem!

This error should be fixed with the newest release. Please re-open in case you end up running into the problem again.
