### ISSUE TITLE
typo in LearnDiscreteCLT

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#2115]
![image](https://user-images.githubusercontent.com/31780210/121966476-be567100-cd3c-11eb-9ca6-bf097277a5bb.png)

(more generally, can I edit the text on various widgets, and if so how?)

**Comment by Planeshifter** [comment]
Thanks for filing this issue! Will be fixed in next editor release.

**Comment by gweinberg** [comment]
> however, it applies instance-wise, for example for all courses hosted at https://isle.stat.cmu.edu. 
> Soonish, designated instructors should also have the ability to use this feature.

I'll have to take a look.  It sounds like you mean for instance that if I edit something on a Learn widget, that change automatically takes place on all lessons on isle.stat.cmu.edu?  Even for courses that aren't mine?  If that's the functionality, then in general that could be problematic.

**Comment by Planeshifter** [comment]
Correct, which is why it's currently constrained to administrators of an ISLE instance. Will follow-up via email.

**Comment by gweinberg** [comment]
Gotcha.
Maybe in future iterations, there could be a way in the editor (or online, wherever the edits are made by administrator) to tag and keep track of multiple versions of a widget.
