### ISSUE TITLE
Pages -> component wizard -> pagination:  menu is missing "both"

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#2123]
![image](https://user-images.githubusercontent.com/31780210/122268405-05ae4000-ceaa-11eb-9fa7-c644ae0bfe03.png)

(I do see, however, that if you select "top" or "bottom", you can then change it to "both" by hand in the code)

**Comment by Planeshifter** [comment]
Thanks for reporting this bug! This will be fixed with the next editor release.
