### ISSUE TITLE
[typo]: Toolbox -> Tests:  "chi square" 

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#2137]
I didn't used to think about this until [Joel ](http://www.stat.cmu.edu/~joel/)corrected me, but it is [more frequently called "chi square" not "chi squared"](https://www.proz.com/kudoz/english/mathematics-statistics/723589-chi-square-or-chi-squared.html) (the current title of the Wikipedia entry notwithstanding).  

In class, I now say "chi square."  I think, if nothing else, that may have pedagogical advantages, because I seem to recall that when I used "chi square**d**," students thought they needed to square extra things.

We can discuss which way we want to do it, but I think all the various locations of ISLE should be consistent:

![image](https://user-images.githubusercontent.com/31780210/123149640-77990300-d42f-11eb-99cf-78d6c00c35b8.png)

Therefore, it's my opinion that the toolbox should be updated:

![image](https://user-images.githubusercontent.com/31780210/123146575-0b68d000-d42c-11eb-9893-fa58ee9e52cf.png)

**Comment by Planeshifter** [comment]
The label in the toolbox now reads "Chi-square Independence Test".
