### ISSUE TITLE
[enhancement]: SelectMatrix -> Actions-> Extended should show TEXT of choices

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#2142]
Currently, from instructor view, **SelectMatrix -> Actions -> Show Extended** shows only the coding of the order of the choices, instead of the text of the choices:

![image](https://user-images.githubusercontent.com/31780210/123266780-533e3480-d4ca-11eb-88d2-5bf62d19244b.png)

Request for that to be updated to show the text of the choices instead of the code numbers for the order of the choices.

**Comment by Planeshifter** [comment]
This improvement has now been implemented and will ship with the next editor release. Thanks for filing this enhancement request!
