### ISSUE TITLE
[bug]: "minimize" tooltip is cut off by edge of browser

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#2171]
On Firefox 89.0.2, browser font = 16 pt, browser zoom=120%, the following happens:

![image](https://user-images.githubusercontent.com/31780210/124136779-14245c00-da53-11eb-9e42-91e504cf9531.png)

Recommend that if, for instance, the button being clicked is more than a certain fraction of the way to the right edge of the browser, then such tips should pop to the *left*

**Comment by Planeshifter** [comment]
With the next release, the minimize tooltip will be displayed to the left. Thanks for noticing this!
