### ISSUE TITLE
[Bug]: \bm no longer parsing in LaTeX

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#2197]
### Description

Several versions of the editor ago, I saw the the LaTeX command \bm{} didn't parse (so I did a workaround by bolding and italicizing).

In a more previous version of the editor, I discovered that the LaTeX command \bm{} parsed  correctly.

However, in the current version of the editor, I see that \bm{} doesn't work again.

For instance:  
https://isle.stat.cmu.edu/36-200-second-summer-21/lab3/
currently yields:
![image](https://user-images.githubusercontent.com/31780210/125493006-c1301438-26f4-4a74-ab6a-08cd13c5e88c.png)

Whereas the same file from a previous version of editor, the desired boldmath worked correctly,e.g., https://isle.stat.cmu.edu/36-200-first-summer-21/lab3/ :

![image](https://user-images.githubusercontent.com/31780210/125493676-c6889969-fd35-4a3e-b41a-553617388b98.png)

### To Reproduce

(see above)

### Version

0.76,1

### Link to ISLE lesson

see above

### ISLE Code

```jsx
**Recall (from lecture 4) that equation of the regression line through data has the form:** $$\bm{\hat{y} = b_0 + b_1x}$$ **where $\bm{\hat{y}}$ is the predicted response, and $\bm{b_0}$ and $\bm{b_1}$ are the computed intercept and computed slope, respectively.**
```

### What browsers are you seeing the problem on?

Firefox

### What browser version?

90.0

**Comment by Planeshifter** [comment]
Just noticed this myself...

For accessibility reasons, we recently switched the underlying LaTeX renderer in ISLE from KaTeX to Mathjax. Turns out the latter doesn't support `\bm`, see this issue: https://github.com/mathjax/MathJax/issues/1219.

It looks like `\mathbfit` is a good substitute for `\bm`, which we should use going forward.
