### ISSUE TITLE
Interval Plots

### ISSUE THREAD

**Issue by sastoudt** [isle-project/isle-editor#2235]
### Problem

As part of EDA it can be helpful to visually compare means between levels of a categorical variable with uncertainty quantified.

### Solution

An interval plot shows the confidence interval for the mean of the data per category. 

### Alternatives

The mean and standard deviation per category can be computed in table form, but it's a little harder to compare across multiple groups quickly. 

### Additional context

None.

**Comment by Planeshifter** [comment]
Thanks for this suggestion!

Starting with the next release (should be out in about two weeks), the data explorer will support the creation of interval plots.

See below for an example:

![image](https://user-images.githubusercontent.com/1913638/127192679-d1202e2b-1598-4280-b7b0-0550be4310d2.png)
