### ISSUE TITLE
Model Diagnostics: Histogram of Residuals

### ISSUE THREAD

**Issue by sastoudt** [isle-project/isle-editor#2236]
### Problem

When assessing whether the residuals of a model are normal, the QQ plot alone can be less intuitive to interpret.

### Solution

Add an additional diagnostic plot option to display a histogram of the residuals. This could even be used side by side with the QQ plot to give students an opportunity to compare the two when learning what the QQ plot is.

### Alternatives

Calculate the residuals and add them as a new column to the pre-existing data. Then make a histogram of this. (might be a bit unwieldy to use regularly)

### Additional context

None.

**Comment by Planeshifter** [comment]
WIth the next version of the editor, both the simple linear and multiple regression components will return a histogram of the residuals alongside the normal QQ plot as their diagnostic plots.
