### ISSUE TITLE
suggestion for different placement of "right/wrong" flags

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#2252]
### Problem

In the following, the "correct/incorrect" flags could be mistaken for labelling the button they're sitting on top of, rather than the button they're pointing to:

![image](https://user-images.githubusercontent.com/31780210/127750319-f3ce6b7b-1504-455e-a04e-528aefb0a480.png)

![image](https://user-images.githubusercontent.com/31780210/127750415-b759f875-cedd-407a-8602-07827f51c6d6.png)

The border of the flag even takes on the background color of the bar it's sitting on, enhancing the confusion:

![image](https://user-images.githubusercontent.com/31780210/127750469-3466e0e1-c2a9-468d-a996-202b061f75c8.png)

### Solution

In that context, I think a clearer flag style/placement would be to have it sit on top of the button it's labelling, and maybe the arrow points left instead of up.

I do understand that we don't want it covering up the text though, not sure what the right solution for that is.

Maybe just tweak the style, like, a more prominent (maybe diagonal) arrow on the flag, and have it be "attached" to the middle of the bar *vertically* as well as horizontally (see below)?  And have the border and maybe background color of the flag correspond to the color of the bar?  Or maybe, slightly darker, and when you mouse-over the bar, it gets highlighted in the same shade as the flag, like:

![image](https://user-images.githubusercontent.com/31780210/127750614-acdf1cac-8008-4ce1-ab8f-08b4da017062.png)

Also notice, it helps if the body of the flag isn't vertically centered on the bar it's on top of, but rather is a bit closer to the bar it's labelling

### Additional context

None.

**Comment by Planeshifter** [comment]
Did some refactoring, current iteration looks like this:

**Comment by gweinberg** [comment]
better.  Too bad we can't change the style of the arrow

**Comment by Planeshifter** [comment]
Yeah, it would be quite complicated. One would have to rewrite it from scratch and not rely on the component currently used.

**Comment by Planeshifter** [comment]
Closing for now, we can revisit later if need be. As of now, I believe that the effort to build custom pointed arrows is too much for what would likely only be a modest improvement.
