### ISSUE TITLE
request some Panel functionalities in SelectQuestionMatrix

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#2257]
### Problem

Currently, SelectQuestionMatrix displays on something that otherwise renders like a Panel, but it doesn't have Header (or Footer, or other similar features that Panel has like minimizable)

### Solution

Request for added functionality in SelectQuestionMatrix similar to Panel functionality (e.g., Header*, Footer, minimizable, etc.)

(*or Title like in Pages)

### Additional context

None.

**Comment by Planeshifter** [comment]
Thanks for this suggestion!

Starting with the next editor release, one will be able to pass any properties of the `<Panel />` component to the select question matrix via the `panelProps` property. For example,

```
<SelectQuestionMatrix
   rows={['Row label']} cols={['Column label']} options={{ '0:0': ['Option'] }} panelProps={{ minimizable: true, header: 'Question Header' }} />
```

will render to 

![image](https://user-images.githubusercontent.com/1913638/128087411-02dde9ae-567a-477b-81cb-ee78816f4e3a.png)

**Comment by gweinberg** [comment]
Cool!  [I assume it will be accessible from the gear icon of the element?  I guess, an extra checkbox to activate "panel properties", and then I guess sub-checkboxes for each panel property]
