### ISSUE TITLE
[Bug]: transform -> combine categories, can't select new names

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#2277]
### Description

Not sure which version of the editor this was from, but for instance go to:
https://isle.stat.cmu.edu/36-200-first-summer-21/okcupid_project2/
select Transform -> rename or combine categories.

Then, you can't use the widget, because every time you try planting the cursor in a "new name" box, the row merely jumps up and down, you can't select/delete/change any of the "new names."

### To Reproduce

see above

### What browsers are you seeing the problem on?

Firefox

### Additional context

also happened with a student on (I think) a mac, so I know it's not just me.

**Comment by Planeshifter** [comment]
Thanks for bringing this to attention! 

Worked on a fix which will be included in the next release. As a temporary remedy, I noticed that when using "Tab" to cycle between the input fields they do not lose focus and one is able to enter the text as expected.
