### ISSUE TITLE
[Bug]: No histogram in model diagnostics for single linear regression with a "group-by" variable

### ISSUE THREAD

**Issue by sastoudt** [isle-project/isle-editor#2296]
### Description

This is related to [this solved issue](https://github.com/isle-project/isle-editor/issues/2260) and [this completed feature request](https://github.com/isle-project/isle-editor/issues/2236).

Now when I click model diagnostics for a single linear regression that has a "group-by" variable I get two diagnostic plots (thank you!), but not the histogram. 

### Expected behavior

Three model diagnostic plots:

- Residuals v. Fitted Plot
- QQ Plot
- Histogram of Residuals

### To Reproduce

1. Go to "Models".
2. Click on "Simple Linear Regression".
3. Choose an outcome, explanatory variable, and a group by variable.
4. Click "Generate".
5. Under the output table click on "Model Diagnostics".

### Version

0.76.4

### Link to ISLE lesson

example in Bucknell lab4_draft

**Comment by Planeshifter** [comment]
Starting with the next editor version, the grouped regression diagnostic plots will now also contain a histogram of the residuals. Thanks for filing this issue!
