### ISSUE TITLE
[Bug]: at browser resolution over 100% some editor menus get cut-off 

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#2322]
### Description

Not sure if this is already logged (if so, feel free to close or merge).  With browser resolution at 120% and font at 16 pt, sometimes some sub-menus inside "Select Component to Insert" get partially cut-off by the editor frame; for instance:

![image](https://user-images.githubusercontent.com/31780210/131260236-32c824ab-54be-4610-8b5a-bd94e830ae2e.png)

![image](https://user-images.githubusercontent.com/31780210/131260359-12e4fc7d-3c9a-4ea8-9b36-4c50c3535911.png)

![image](https://user-images.githubusercontent.com/31780210/131260443-1f1a9066-c9ef-478b-8ccd-56c2af241e72.png)

### To Reproduce

right-click in editor, in various configurations

### Version

0.76.4 (Windows)

### What browsers are you seeing the problem on?

Firefox

### What browser version?

91.0.2

### Additional context

I imagine the solution would require complicated new functionalty so the menus would dynamically re-configure themselves if they detected that they would get cut off by the frame; hence I understand that it's something for probably the far future.

**Comment by Planeshifter** [comment]
Tweaked the positioning logic a bit so that with the next editor release, this shouldn't happen anymore. The sub-menus should be moved down a bit to accommodate for the overlap whenever their height exceeds the window. Please re-open if the issue is still reproducible with the next editor update.
