### ISSUE TITLE
Have ability to select custom color for legends in clustered bar charts

### ISSUE THREAD

**Issue by ogilani** [isle-project/isle-editor#2324]
### Problem

It seems like right now, we can't manually change the legend colors of a clustered bar chart. 

### Solution

In this clustered bar chart below, the response variable is “Favorite starburst color”. It would be nice if the bar representing “Red” could actually be red instead of blue. 
<img width="674" alt="IMG_6529" src="https://user-images.githubusercontent.com/7502054/131365669-737be0f5-06da-429e-a5bc-ebfc395c04c9.png">

### Additional context

None.

**Comment by Planeshifter** [comment]
This will become possible with the next editor release, alongside the ability to color the slices of pie charts and the bars in a non-grouped bar chart.
