### ISSUE TITLE
[Bug]: Correlation is broken in version 0.76.5 (Mac)

### ISSUE THREAD

**Issue by ogilani** [isle-project/isle-editor#2363]
### Description

When calculating the correlation between two quantitative variables, I get the error: 
![image](https://user-images.githubusercontent.com/7502054/132890493-4c6650b4-b06a-45cb-b2a2-316a37724842.png)

The "Correlation Matrix" function works fine though. 

### To Reproduce

1. Go to Statistics
2. Select Correlation
3. Enter one variable in "Variable(s)" field
4. Enter the second variable in ""Second Variable" field. (I also tried entering both variables in the "Variable(s)" field).
5. Hit Calculate

### Version

0.76.5

### Link to ISLE lesson

https://bucknell.kymetis.com/Math216-06-Fa21/lab4_test/

### What browsers are you seeing the problem on?

Chrome

**Comment by Planeshifter** [comment]
Worked on a fix, which will be included in the next editor release.
