### ISSUE TITLE
[Bug]: Clicking on "Settings" cog-wheels in a widget freezes ISLE-editor

### ISSUE THREAD

**Issue by ogilani** [isle-project/isle-editor#2364]
### Description

If I have a widget placed and I want to learn about more functionalities or options, I used to click the settings cog on the widget. However, since updated to 0.76.5, when I do that, isle-editor goes blank (white), and I have to close it. 

### To Reproduce

1. Insert a widget (like DataExplorer)
2. Click on settings icon in top right hand corner.

### Version

0.76.5

**Comment by Planeshifter** [comment]
Worked on a fix, which will be included in the next editor release.
