### ISSUE TITLE
[Bug]: "Split by" option broken in scatter plot when adding regression model

### ISSUE THREAD

**Issue by ogilani** [isle-project/isle-editor#2367]
### Description

When trying to add a regression line to a scatter plot, split by a categorical variable, the option to "Split By" does not let you select any variables in isle-editor version 0.76.5

### To Reproduce

1. Go to Plots -> Scatterplots -> select your X and Y variables, add a categorical variable to symbol
2. Check the box for "Show Regression Model"
3. Try to add a categorical variable for "Split By", but the dropdown menu does not work.

### Version

0.76.5

### Link to ISLE lesson

https://bucknell.kymetis.com/Math216-06-Fa21/Lab_4-Least_Squares_Regression/

**Comment by Planeshifter** [comment]
Thanks for filing this issue! I can reproduce it and will work on a fix ASAP. Will be in touch with respect to re-uploading the lesson in a timely manner if needed.

**Comment by Planeshifter** [comment]
Okay, this will be fixed with the next release. Closing and following-up via email.
