### ISSUE TITLE
Control the parameters for density line overlaid on histogram

### ISSUE THREAD

**Issue by ogilani** [isle-project/isle-editor#2405]
### Problem

Currently, it is possible to make a histogram with a density line overlaid on it. We have the choice of which distribution to overlay on the histogram (e.g. Normal density curve). However, we cannot specify the parameters of this density curve; ISLE calculates the mean and sd of the data and uses those parameters. It would be be nice to be able to specify the mean and sd so that if I wanted to see how the empirical distribution compares to a theoretical density curve, I could overlay the theoretical density curve on the histogram by specifying the mean/sd. 

### Solution

The default option could be "Calculate parameters from the data", and there could be an additional option "Specify distribution parameters". Checking that would create "p" boxes where we can set the values of the "p" parameters for the distribution (where "p" would be 2 for Normal, 1 for T, 1 for Chi-sq etc). 

### Additional context

None.

**Comment by Planeshifter** [comment]
This feature request has now been implemented and will be a part of the next editor update.
