### ISSUE TITLE
[Bug]: in report, highlight text -> ctrl+c doesn't copy, it changes to (code?) font

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#2406]
### Description

In the report editor on Windows, highlight text -> ctrl+c, the expected behavior is that it would copy the selected text, but that's not what happens, it toggles the font face to (what I'm guessing is code font?  it's small and red).

And the selected text is definitely not added to the clipboard, because plant cursor -> ctrl+v doesn't paste the text, it pastes whatever the previous object was on the clipboard. 

### Expected behavior

highlight text -> ctrl+c should copy the selected text.

### To Reproduce

https://isle.stat.cmu.edu/36-200-Fall21/diamonds_project1/  -> report editor -> type some text -> highlight -> ctrl+c.

### What browsers are you seeing the problem on?

Firefox

### What browser version?

92.0

**Comment by Planeshifter** [comment]
Thanks for bringing this bug to my attention!

Starting with next update, Ctrl+C will copy again as expected per changes in edf13545140baa52f55cd7ee529b161b155b2bc9.

**Comment by gweinberg** [comment]
cool.
You will also need to change the "code font" button:
![image](https://user-images.githubusercontent.com/31780210/135176610-e2992b36-b879-4acd-81a9-5db243a719db.png)

(personally I'd vote for removing; but if you want to keep it, you'll need to map its shortcut to a different set of keystrokes, maybe ctrl+D?  And then you'll also need to update the tooltip popup on the button as well.
