### ISSUE TITLE
Jitter data points in scatterplot

### ISSUE THREAD

**Issue by sastoudt** [isle-project/isle-editor#2444]
### Problem

When students are working on real data in a project setting, they might be facing situations where many points are on top of one another (e.g. x-axis is age, y-axis is something more continuous). To better see what is going on, it might be helpful to have "jitter" capabilities for each axis in the scatterplot. 

### Solution

An option in the scatterplot pane (maybe a checkbox for each axis?) that allows for a baseline jitter (no need to let students customize the value). Looking to [R solutions](https://jmw86069.github.io/splicejam/reference/jitter_norm.html) for [default jitter](https://github.com/SurajGupta/r-source/blob/master/src/library/base/R/jitter.R) amounts might be helpful.

### Alternatives

As a hack, I've tried to generate random values from a normal distribution with mean zero to add to my data to get the jittered effect. The tricky piece here is picking the right standard deviation to get the jitter effect v. just completely changing the data. Generalizing this for all of the data scenarios for my students/finding a good rule and then telling students to go through this 3-step process seems a bit unwieldy.

### Additional context

None.

**Comment by Planeshifter** [comment]
Thanks for this suggestion!

We have added the feature to add jitter to the values of either axis via a checkbox. This will be a part of the next editor update.
