### ISSUE TITLE
[Bug]: "ComponentDocs" printed multiple times in descriptions, in Component Wizards

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#2446]
### Description

In the latest version (0.76.7) of the editor, inside any ComponentWizard, the descriptions of every item has "ComponentDocs" printed over and over.  For instance, see screenshot:
![image](https://user-images.githubusercontent.com/31780210/136041378-17025b2c-9d5a-4e08-a44f-c0154afcd9d5.png)

### To Reproduce

editor version 0.76.7 on Firefox -> open any ComponentWizard

### Version

0.76.7

### What browsers are you seeing the problem on?

Firefox

### What browser version?

93.0

**Comment by Planeshifter** [comment]
Thanks for reporting! Looking into it...

**Comment by Planeshifter** [comment]
This is now fixed per 83347b599c8a2ce7ccbd26dbe182c2edb178b7cc. Getting another update out as I imagine most instructors haven't updated yet.

**Comment by Planeshifter** [comment]
GitHub currently has performance issues that prevent me from releasing an update: 

https://www.githubstatus.com/incidents/bdbzpz7qxmbx

Will get it out as soon as these are resolved.

**Comment by Planeshifter** [comment]
Update has been released.
