### ISSUE TITLE
Multiple Comparisons test (Tukey HSD) for ANOVA

### ISSUE THREAD

**Issue by ogilani** [isle-project/isle-editor#2506]
### Problem

It would be nice to have the ability to do a multiple comparisons test like Tukey's HSD after determining that at least two means are different from each other. 

### Solution

A test that shows pair-wise comparison of means, and labels which means are not statistically significantly different from each other and which are (e.g. HSD.test in the R package agricolae) as well as a plot show the confidence intervals for pair-wise difference in means which maintains the correct family-wise error rate (e.g. plot(TukeyHSD(...)) in R). 

### Additional context

None.

**Comment by Planeshifter** [comment]
This test has now been added.
