### ISSUE TITLE
alpha level selector for Interval Plots not working

### ISSUE THREAD

**Issue by ogilani** [isle-project/isle-editor#2530]
When creating an interval plot, there is an option to set the significance level alpha. But that does not seem to be working - changing it to anything other than the default changes the value to 0, and the interval plot is created with interval widths of 0. I am using version 0.76.6 of ISLE editor.

**Comment by Planeshifter** [comment]
Thanks for bringing this to my attention!

Problem will be resolved per commit 9f95f8969d28330f3cc22279798aa0f9382bb468. Plan is to have an editor update out this week, which will contain the bug fix.
