### ISSUE TITLE
[Bug]: Multiple Linear Regression not working with missing values

### ISSUE THREAD

**Issue by ogilani** [isle-project/isle-editor#2531]
### Description

If the dataset has missing values, fitting a MLR model to a quantitative response but only categorical predictor(s) does not produce any output, even if the "Omit missing values" box is checked (the output produced has NaNs for all entries). If the quantitative variable is quantitative, then it is not a problem. The problem seems to be with categorical predictors only. I was trying to fit a MLR with categorical predictors to get the residual plots to check ANOVA conditions.

### To Reproduce

1. Go to Toolbox
2. Select Models, Multiple Linear Regression
3. Select the quantitative response variable
4. Select a categorical explanatory variable.
5. Check "Omit missing values"

### Version

0.76.6

### Link to ISLE lesson

https://bucknell.kymetis.com/Math216-06-Fa21/Group_2-Good_Guys-HumanFreedomIndex/

### What browsers are you seeing the problem on?

Chrome

**Comment by Planeshifter** [comment]
Can reproduce. Am investigating and will report back as soon as possible.

**Comment by Planeshifter** [comment]
This has meanwhile been fixed; issue was that missing values in the response variable were not filtered out. It only worked for the quantitative predictors in the given dataset because the predictors had missing values for the same observations as the respone.
