### ISSUE TITLE
User customization options

### ISSUE THREAD

**Issue by ciaran-evans** [isle-project/isle-editor#254]
Would be nice to have a couple customization options in the editor
- default working directory for opening and saving files (rather than the isle-editor repository, would be nice to save a path to a folder where the user stores .isle files, to avoid navigating each time opening a file
- default split of editor and preview windows (otherwise user might be re-sizing this split each time they open the editor)

**Comment by Planeshifter** [comment]
Thanks for these suggestions, which I believe would both improve usability of the editor! I will look into implementing these two features in the coming days.

**Comment by Planeshifter** [comment]
Made the following changes to the most recent version of the editor:

- the split position of the two panels should now correctly be restored upon exiting and restarting the editor
- the "open file" dialog will default to the latest opened directory, whereas the "save-as" dialog will default to the directory of the file to be saved

Closing this issue.
