### ISSUE TITLE
[Bug]: tests->chi square, code still needs "chi squared"

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#2556]
### Description

 pertaining to #2137, we changed the name of the test to "chi square" as it appears in data explorers.

However there is now an inconsistency with what the code requires, since specifying:

tests={["Chi-square Independence Test"]}

renders an empty test; it still requires:

tests={["Chi-square**d** Independence Test"]}

Of course, in the parser, if you change the name of the test to "Chi-square ...", then legacy code will break.  Is there a way to make it so that *either* of the above will work in the code?

### To Reproduce

see above

### Version

0.76.10, Windows

### What browsers are you seeing the problem on?

Firefox

### What browser version?

94.0.1

**Comment by Planeshifter** [comment]
Yes, that should be possible. Will look into this.

**Comment by Planeshifter** [comment]
Change in https://github.com/isle-project/isle-editor/commit/83265f72a99839828f9db4247d2f2d5b670ae565 will allow one to specify the test with `Chi-square Independence Test` but preserve rendering the menu when the array of tests contains `Chi-squared Independence Test`, as suggested.
