### ISSUE TITLE
recent file conflict between 'npm run dev' and 'npm start'

### ISSUE THREAD

**Issue by ciaran-evans** [isle-project/isle-editor#256]
The following work flow appears to have a problem (at least on my machine):

- use npm run dev to open ISLE editor
- in editor, edit a lab file (say, lab03). Save. 
- close ISLE editor
- use npm start to re-open ISLE editor
- in editor, open lab03. Make more changes. Save.
- close ISLE editor
- use npm run dev to re-open ISLE editor
- the default is now that the editor opens the most recent file you were working on. However, this seems to open the last version of the file you were working on **in npm run dev**, not the version that was edited through npm start

**Comment by Planeshifter** [comment]
Yes, the dev or built versions will use their own localStorage and not be in sync. Won't change this behavior as it only effects development usage.
