### ISSUE TITLE
[Bug]: chi square output says "chi-squareD"

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#2579]
### Description

pertaining to #2137, we still need to change the terminology on the chi square output, which still says "chi-square**d**" not "chi-square":

![image](https://user-images.githubusercontent.com/31780210/144727561-ffcd46f6-5722-4faf-9996-76b47ef2f866.png)

### To Reproduce

any currently posted data explorer -> run chi square test

**Comment by Planeshifter** [comment]
@gweinberg The chi-square independence test is one of the few remaining outputs in the data explorer that is currently executed via R, from which we obtain above test result printout. We can revisit this issue once moving to our own implementation and then use "chi-square" instead of "chi-squared".

**Comment by gweinberg** [comment]
Ok thanks for the update!

**Comment by Planeshifter** [comment]
Found a way to edit the printed R model output accordingly. Closing.
