### ISSUE TITLE
features: select more than one density overlay on histogram; and tool tip explanation

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#2694]
### Problem

Three feature requests:

1) On histogram -> density -> overlay line, it would be cool if more than one density type could be selected, so that users could compare how similar they are.  [So, for instance, "data driven" and "Normal", as a (non-QQplot) indication of how Normal the data are.]

2) On histogram -> density -> overlay line -> **data driven**, there perhaps should be a tooltip popup, explaining briefly what exactly is being constructed with the "data driven" curve, or what algorithm is being run to produce it.

[edited to add]:

3) could we add more overlay types?  Like, t distribution, chi square distribution, etc (although it would need to have a place to enter the relevant degrees of freedom, which might require a more significant interface redesign)

### Solution

see above

### Additional context

None.

**Comment by Planeshifter** [comment]
These suggestions have now all been implemented and will be a part of the next release.
