### ISSUE TITLE
[Bug]: Bar chart of answers is in reverse order from order of choices

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#2695]
### Description

On the select-all-that-apply question screenshotted below, the top-to-bottom order of the choices is:

unimodal
skewed left
skewed right
linear
nonlinear
postive association
negative assocation
postive association then negative assocation:

![image](https://user-images.githubusercontent.com/31780210/157948249-b6b23f70-8de0-4101-8e3a-6970b9889dd5.png)

But in the bar chart of the responses, the top-to-bottom order of the choices is reversed:

![image](https://user-images.githubusercontent.com/31780210/157948378-64c18b6c-6e3d-4193-925a-8635259f13a9.png)

I think the bar chart of the responses should have the same top-to-bottom order as the choices in the exercise.

### To Reproduce

https://isle.stat.cmu.edu/36-200-spring22/lab3/ -> question1a -> answers

### Version

I don't remember what version that assignment was made in

### Link to ISLE lesson

https://isle.stat.cmu.edu/36-200-spring22/lab3/ 

### What browsers are you seeing the problem on?

Firefox

### What browser version?

97.0.2

**Comment by Planeshifter** [comment]
Thanks for filing this issue! With the upcoming editor release, the order of categories of the bar chart inside the response visualizer has now been reversed.
