### ISSUE TITLE
request for "create filtered data" button to be moved to top of spreadsheet

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#2720]
### Problem

I'm reminded of this problem every semester that we have project 2 (which is when the students tend to filter data in order to justify various formal procedures):  The students never see the "create filtered dataset" button.  

Since, when you filter data, you're looking at the top of the spreadsheet (since the filter functions are at the top of a column), it would be better if the "create filtered dataset" button were above, rather than below, the spreadsheet.  Ideally, it would appear immediately above the spreadsheet, just below the "variable descriptions" button.  

I think the "number of rows" indicator should also be moved for the same reason (or maybe duplicated above the spreadsheet as well as below).

### Solution

see above

### Additional context

None.

**Comment by Planeshifter** [comment]
The suggestions laid out in this issue thread have now been implemented.
