### ISSUE TITLE
[Bug]: new categorical variable doesn't appear in boxplot on mac chrome if space in name

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#2722]
### Description

From a student:

On Chrome, on a mac, go to:
https://isle.stat.cmu.edu/36-200-spring22/food_project2/  
-> transform -> rename-or-combine-categories -> sugar -> rename categories 1,2,3 as "1", rename categories 4,5,6 as "2", and rename categories 7,8,9,10 as "3" ->
name new variable "sugar combined" (with a space, that's what causes the bug) ->
then toolbox -> plots -> boxplot -> variable=energy, and for "group by" he wants to select the new variable but it doesn't appear, that's the bug.

I don't know if it's unique to boxplot or if it's all toolbox tools that use categorical variables (he didn't try).

When he puts a dash instead of a space in the new variable name, the bug doesn't happen.

On Firefox on Windows the bug doesn't happen to me (boxplot happily shows the new variable even with a space in the name)

Solution would be for ISLE to force something like an underscore in new variable names if user puts a space.

### To Reproduce

see above

**Comment by Planeshifter** [comment]
Using spaces in variable names is now forbidden per commit d7d362b4fcf11e1621eb38812446cb4aa3b3aba8.
