### ISSUE TITLE
request for RangeQuestion:  ntries, and different feedback style

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#2723]
### Problem

I notice that currently, RangeQuestion doesn't have a multiple tries functionality, and it gives feedback like NumberQuestion.  I think it should allow multiple tries, and I think it should give endpoint-specific feedback like SelectQuestionMatrix:

1) Request for RangeQuestion allow something like:

submitAfterFeedback
nTries={3}

2) Request for RangeQuestion to give feedback like SelectQuestionMatrix, i.e.:

* If, in RangeQuestion, both endpoints are wrong, then below both endpoints "try again" appears like in SelectQuestionMatrix and "you have two more tries" pops up (if nTries={3} is enabled; otherwise, the correct answers appear in red, separately below each endpoint);

* If, in RangeQuestion, one endpoint is correct and one is wrong, then "correct" appears below the correct endpoint (like in SelectQuestionMatrix) and "try again" appears below the wrong endpoint and "you have two more tries" pops up (if nTries={3} is enabled; otherwise, below the wrong endpoint, the correct answer appears below it in red);

* If, in RangeQuestion, both endpoints are correct, then "correct" appears below each endpoint, like in SelectQuestionMatrix.

### Solution

see above

### Additional context

None.

**Comment by Planeshifter** [comment]
Thanks for filing this request and offering these suggestions, which all seem sensible to me! Putting it on the TODO list; confident I can have it included in the next editor release.

**Comment by Planeshifter** [comment]
The component has now been updated according to the suggestions laid out in this issue thread.
