### ISSUE TITLE
[Bug]: Student identifiers don't appear in select student responses

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#2766]
### Description

Lesson -> Instructor panel -> select student responses -> pulldown to select student, none of the student identifers appear:
![image](https://user-images.githubusercontent.com/31780210/170696600-02d8bd36-2faf-47c0-b26c-c29027bdd5f4.png)

That's in Firefox 100.0.2, at 100% broswer resolution.

I'm guessing it's a margin/wrapping/width issue, it's probably trying to mimic the width of the columns in the progress pane or something.  It's reminiscent of other edge-of-window problems across ISLE.

### Expected behavior

student identifiers appear

### To Reproduce

Firefox 100.0.2, on Win10, at 100% broswer resolution -> https://isle.stat.cmu.edu/36-200-first-summer22/lab4/ -> Instructor panel -> select student responses -> pulldown to select students

**Comment by Planeshifter** [comment]
Thanks for filing!

Backend server had to be updated as part of the migration from using a single "name" field for users to storing their first names, preferred names, and last names individually. Names should now show up on the isle.stat.cmu.edu instance in all lessons.

**Comment by gweinberg** [comment]
Yep, fixed!
