### ISSUE TITLE
[Bug]: applet in IFrame doesn't appear 

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#2802]
### Description

When embedding an applet in an IFrame, it doesn't appear in browser.

See, for instance:
https://isle.stat.cmu.edu/36-200-second-summer22/Standard-Normal-applet/
and
https://isle.stat.cmu.edu/36-200-second-summer22/lab6/ (scroll all the way down)

### To Reproduce

see above

### Version

0.76.16

### What browsers are you seeing the problem on?

Firefox

### What browser version?

101.0.1

### Additional context

we've encountered this before; you did something by hand that made it work in one instance, but I don't know what it was, or what the general solution is.

**Comment by Planeshifter** [comment]
Yes, I indeed made a change on June 5th to the iframe component that seems to have resolved the problem. This fix will be included in the next editor release. In the meantime, please let me know the affected lesson(s) and I will re-upload them with the fix applied.

**Comment by Planeshifter** [comment]
(an alternative solution is to use a simple `<iframe` instead of our `<IFrame` component; however, this means that the buttons to open in another window or make the applet fullscreen won't be visible)

**Comment by gweinberg** [comment]
great thanks.  This is for second summer semester, so as long as the new release is out by July 17 it should be good.

**Comment by gweinberg** [comment]
glad this is done, is the new editor released yet?  I see version 0.76.16 on isledocs.  Is there a date-stamped version release history anywhere?
