### ISSUE TITLE
request: Edit Cohort to accept space delimited, tab delimited, etc

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#2845]
### Problem

When downloading course rosters from Canvas or SIO, even as a csv they open in excel formatted in columns.  When I copy/paste the column of student identifiers into the Edit Cohort window, currently ISLE interprets it as a single long identifier, and I end up having to add all the commas by hand

### Solution

change Edit Cohort to accept delimiters such that it properly understands columns pasted from Excel

### Alternatives

A possible workaround:  Add a button to the Edit Course panel to the effect of "click here to convert to comma delimited if needed" and it opens up the following website in a new window:
https://convert.town/column-to-comma-separated-list
(here's their front page, very cool: https://convert.town/)

### Additional context

None.

**Comment by Planeshifter** [comment]
This will be resolved with the next dashboard update, which will split newline delimited data (as copied from Excel) going forward per https://github.com/isle-project/isle-dashboard/commit/9a3dcb62052b38060980e088c98a88fe1d85024b. Thanks for filing this issue!
