### ISSUE TITLE
[Bug]: RangeQuestion -> Answers

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#2903]
### Description

Firefox 104.0.2 -> https://isle.stat.cmu.edu/36-200-Fall22/lab2/ -> question 3b (the range question) -> click "Answers", yields the following error:
![image](https://user-images.githubusercontent.com/31780210/188687144-1d217cfe-b4dc-4081-9dd4-e09361b9d576.png)

### To Reproduce

see above

### Version

0.76.17 Windows NT

### Link to ISLE lesson

https://isle.stat.cmu.edu/36-200-Fall22/lab2/

### ISLE Code

```jsx
<RangeQuestion
    id="q3b"
        question="3b. What is the range of WBC values for the first bin?"
        solution={[0.9,3.09]}
    />
```

### What browsers are you seeing the problem on?

Firefox

### What browser version?

104.0.2

### Additional context

here's the toggle stack trace of the error:
ullscreenActionDisplay/<@https://cdn.jsdelivr.net/npm/@isle-project/dll@0.50.49/dll.ResponseVisualizer.js:97:8567
renderPlot@https://cdn.jsdelivr.net/npm/@isle-project/dll@0.50.49/dll.ResponseVisualizer.js:97:15919
render@https://cdn.jsdelivr.net/npm/@isle-project/dll@0.50.49/dll.ResponseVisualizer.js:97:18794
Bf@https://cdnjs.cloudflare.com/ajax/libs/react-dom/18.1.0/umd/react-dom.production.min.js:147:310
pi@https://cdnjs.cloudflare.com/ajax/libs/react-dom/18.1.0/umd/react-dom.production.min.js:147:106
Nk@https://cdnjs.cloudflare.com/ajax/libs/react-dom/18.1.0/umd/react-dom.production.min.js:252:139
Qi@https://cdnjs.cloudflare.com/ajax/libs/react-dom/18.1.0/umd/react-dom.production.min.js:195:143
Lk@https://cdnjs.cloudflare.com/ajax/libs/react-dom/18.1.0/umd/react-dom.production.min.js:195:74
Ld@https://cdnjs.cloudflare.com/ajax/libs/react-dom/18.1.0/umd/react-dom.production.min.js:194:439
Mf@https://cdnjs.cloudflare.com/ajax/libs/react-dom/18.1.0/umd/react-dom.production.min.js:187:381
Ki@https://cdnjs.cloudflare.com/ajax/libs/react-dom/18.1.0/umd/react-dom.production.min.js:189:192
bb@https://cdnjs.cloudflare.com/ajax/libs/react-dom/18.1.0/umd/react-dom.production.min.js:79:182
ha/<@https://cdnjs.cloudflare.com/ajax/libs/react-dom/18.1.0/umd/react-dom.production.min.js:184:231

**Comment by Planeshifter** [comment]
This bug is resolved per 4997d8edeadec3dd9bbad510b6ff3e2f8ae655fe. Patch will be out with the next editor release. Thanks for the alert about this!
