### ISSUE TITLE
answers to be included in emailed "finish lesson" document, and "finish lesson" to alert and to not activate if unanswered questions

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#3034]
### Problem

A comment on the recent end of semester course evaluations was that since not all ISLE questions have answers (I'm assuming they're referring to open-ended questions), they often felt like they didn't get feedback.

[Of course we hope that the TAs will go over the answers in lab but evidently that doesn't always happen.]

I'm brainstorming ways to remedy this other than merely a "show answer" button on every exercise (since I'm concerned that would cause students to simply race through the assignment and not participate in lab).

One possible solution is to have answers to questions set to print on the emailed pdf the students get when pressing "finish lesson", even if there wasn't a "show answer" button on the exercise.  Thoughts?

I suppose that once students learned that "finish lesson" gave them all answers, they might simply jump directly to the "finish lesson" button on subsequent lessons.  A solution to that problem would be if "finish lesson" didn't activate unless something had been answered for every question (does it currently have that functionality?)  It would be ideal if pressing "finish lesson" caused the lesson to jump to the first un-answered question, highlighted in yellow like the way it does when clicking from the instructor panel; barring that, it would at least need to pop up something like "there are unanswered questions remaining; please answer all questions before receiving the solutions"

### Solution

see above ideas

### Additional context

None.

**Comment by Planeshifter** [comment]
Both of these suggestions have now been implemented! Thanks for them!

When a new `includeSolutions` property is enabled for the `LessonSubmit` component, solutions for all questions where available will be included in the generated PDF even if the individual questions are configured to not provide question feedback upon submission.
