### ISSUE TITLE
request for option for linear regression test to be added to "tests"

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#3045]
### Problem

Every semester, students don't see where linear regression test is, because it's in the "models" tab instead of "tests."
For pedagogy, it would be useful if we could add a duplicate link to it inside of "tests."

### Solution

just add the option for "linear regression" in "tests".  It would just be a duplicate link to the same linear regression widget currently inside "models."

### Additional context

None.

**Comment by Planeshifter** [comment]
One can now list "Simple Linear Regression" in the `tests` array. For example, we can use

```jsx
tests={["One-Sample Mean Test","Two-Sample Mean Test","One-Way ANOVA","One-Sample Proportion Test","Two-Sample Proportion Test","Chi-squared Independence Test","Simple Linear Regression"]}
```

for the second project.

Caveat: It's not displayed by default if the `tests` are not specified, as I am not convinced it makes sense generally.
