### ISSUE TITLE
on-screen alert if connection to server lost

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#3046]
### Problem

Brainstorming possible solutions to the apparent issues of student reports getting lost or overwritten with previous versions, apparently due to loss of connection to server.

I think the solution is simply for the lesson to ping the server every [however many seconds], and as soon as it doesn't detect a ping-back, it pops up an alert like, "Your connection to the ISLE server has been lost; any changes you make may not be saved.  Download the html file of your report to your local computer, and proceed to a stable internet connection" or whatever; in the same way that gmail pops up an alert if your internet connection is lost.

[I've been trying to brainstorm various schemes for keeping time-stamped track of browser version of report and server version of report, separately, and to have the most-recently-changed take precedence if there's ever a mis-match; but I suspect that's unworkable, first because laptop clock and server clock inevitably won't be on exactly the same time, and also because once you have collaborative editing you run into unreconcilable versioning issues if one or more of the collaborators lost internet.]

### Solution

see above

### Additional context

None.

**Comment by Planeshifter** [comment]
Something like this has meanwhile been implemented. One can also override the default connection lost message via a`connectionLostMessage` property on the `TextEditor` component.
