### ISSUE TITLE
links on info.json should open in new window

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#3088]
### Problem

Currently, web links on the info.json file for a data explorer seem to open in same browser (i.e., to navigate away from the explorer).  For instance, https://isle.stat.cmu.edu/data-explorers/email/ -> description -> click link, it navigates away from the explorer.  [Win10, Firefox 109.0)

Not sure if this requires a change in the editor or whether it could be done in the json, but such links should open in new browser instead.

### Solution

links from info files should open in new broswer (or new tab)

### Additional context

None.

**Comment by Planeshifter** [comment]
Links in the dataset description will now open in a new tab!
