### ISSUE TITLE
request disable history function in report editor

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#3124]
### Problem

happily it looks like there were no large scale issues with our most recent class project :)

The only issue was with one student who had clicked on the history function and ended up deleting the whole report (she was eventually able to get a previous version).  This has happened in the past, with students playing around with the history function and deleting their report.  I think the history tab and the "show history" button and corresponding "restore" functionality is confusing and I recommend a toggle in the code to disable it (there currently doesn't seem to be a show-history on/off toggle in the Data Explorer tools unless I'm not seeing it).

### Solution

a code toggle to disable the history tab and the "show history" button on the report editor.

### Alternatives

alternatively, re-design the show history functionality so it's clearer what happens before you click stuff, and change the word "restore" to "revert", and also have some safeguard popups like, "doing this will revert your report to the way it was 9 days ago, are you sure you want to do this [yes do it / no cancel]"

### Additional context

None.

**Comment by Planeshifter** [comment]
This should already be possible, see the `history` attribute of the [text editor component](https://isledocs.com/docs/text-editor/). In a data explorer, we could set it as follows:

```jsx
<DataExplorer 
  editorProps={{
    history: false
  }}
....
```

Leaving this open so we can track improving the history view UX of the editor to prevent accidental data loss and making its functionality clearer to users.

**Comment by gweinberg** [comment]
Ok good to know it's possible.  Should that option appar in the DataExplorer component wizard?

**Comment by Planeshifter** [comment]
Unfortunately, there is no way to easily have nested properties appear in the component wizard. So we will leave it as-is and require manual input of the key-value pairs which one wants to use:

<img width="996" alt="image" src="https://github.com/isle-project/isle-editor/assets/1913638/78e1a07e-f439-45b1-996f-334557d370f5">

Hopefully this issue can serve as a resource should the same question arise again.
