### ISSUE TITLE
[Bug]: inconsistent toolbox terminology for different directions of tests

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#3134]
### Description

In Toolbox -> tests -> one sample (either mean or proportion) or Toolbox -> tests -> two sample (either mean or proportion), it uses inconsistent terminology under "direction".

For one-tailed tests, it uses inequality terminology ("less," "greater") from the standpoint of the hypotheses; but for two-tailed tests, it uses geometric terminology "two sided" from the standpoint of the distribution.

The terminology should be consistent. 

Actually, I recommend using **both** types of terminology, the primary terminology being the inequality terminology from the standpoint of the hypotheses, and the secondary terminology (which should be in parentheses) being the geometric terminology from the standpoint of the distribution, something like this:

**not equal (two sided)**
**less than (left sided)**
**greater than (right sided)**

Also note I think it should be "less *than*", "greater *than*", not just "less," "greater".

And can we get symbols for the inequalities instead of needing to do it in words?

### To Reproduce

see above

**Comment by Planeshifter** [comment]
This has now been addressed, thanks for the suggestion!
