### ISSUE TITLE
[Bug]: inconsistency in notation between one mean test dialog and one proportion test dialog

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#3136]
### Description

In Toolbox -> Tests -> one-sample mean test, when it asks for the null value it uses the notation "H_0 mean value" (and then it shows mu_0 in parentheses).

But on one-sample proportion test, it's not consistent, it only shows p_0.  It should be:
"H_0 proportion value" (and then the p_0 should be in parentheses)

### Expected behavior

see above

### To Reproduce

see above

**Comment by Planeshifter** [comment]
Changed the description for the null value in the proportion test, and also the correlation test where the same applies.
