### ISSUE TITLE
[Bug]: inconsistent terminology and typography between two-group tests dialog and one-group tests dialog

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#3138]
### Description

in Toolbox -> test of one mean (and also soon to be in test of one proportion, per #3136), the prompt for the null value uses the terminology and notation like:

**H_0 mean value** or **H_0 proportion value**

I.e., it uses terminology from the standpoint of the parameter (and the "0" is subscripted on the "H").

But for test of two means or two proportions, it says:

**Difference under H0**

I.e., it uses the more specialized term "under", which is inconsistent with the one-test panel and which will be more confusing to beginners (and also the "0" isn't subscripted on the "H").

So, a two-part request:

1) request that the language on the two-groups panels be changed to be made consistent with the language on the one-group panels; maybe:

**H_0 value for difference of means** and **H_0 value for difference of proportions**

2) need to sub-script the "0" on the "H"

### To Reproduce

Toolbox -> tests

**Comment by Planeshifter** [comment]
This has now been implemented, thanks for the suggestions!
