### ISSUE TITLE
[Bug]: on Windows, need to ctrl+z *twice* to undo in editor

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#3140]
### Description

On Windows, to undo typing a character in the editor, you have to press ctrl+z **twice** instead of once.  Is this intentional or is it a bug?  [I only recently discovered this; I had always thought ctrl+z simply wasn't enabled in the editor!]

### Expected behavior

I'd expect that to undo a character, I'd press ctrl+z only once

### To Reproduce

windows10 -> editor -> type something -> ctrl+z once, nothing happens -> ctrl+z again -> one character is undone

### Version

0.76.22, Windows NT

### What browsers are you seeing the problem on?

Firefox

### What browser version?

seems to have happened on several versions (I'm currently on 110.0.1)

**Comment by Planeshifter** [comment]
Yes, that's a bug, thanks for reporting! Can reproduce, looking into it.

**Comment by Planeshifter** [comment]
Updating the underlying [Monaco editor](a57eff68642fdb7e943542489791450c8485de81) resolved this issue. Will be included in next editor update.
