### ISSUE TITLE
request for hideable info in "description" of datasets

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#3193]
### Problem

I want to add a dataset to the general repository.  The dataset comes from the website of someone, who I therefore want to reference in the json description; but their website includes the full analysis of the data, and if I use the dataset for homework I don't want students to be able to find their website.

Therefore, request for added functionality to be able to "turn off" certain info in "description" without needing to make a new description.

Maybe something like, a new function that can be added to DataExplorer, maybe something like **showHiddenDescriptionInfo**, and the default would be "true", but if you toggled it to "false" then it hides specified lines from the Description.

I guess that would require certain new markup code in the Description json, which could be put around anything in the description that would be something we might deem sensitive (maybe **sensitive**   **/sensitive**?), and which the editor would be able to then read and act on if **showHiddenDescriptionInfo** was toggled to "false."

An alternative and maybe better idea is below.

### Solution

see above

### Alternatives

An alternative solution might be two different versions of the description for a dataset (maybe an "instructor" version and a "student" version), and a new toggle in DataExplorer like **studentInfo**, whose default would be "false" but if it's toggled to "true" then the editor pulls the other description.

That would, I guess, require two different "Info" calls in the file preamble, one for the regular/default/instructor-version info file, and one for the "student version" info file.

--------------------------------------

Actually, come to think of it, I suppose I could just make multiple versions of the info file, and then call whichever one I want in the preamble, so maybe ignore my request.

### Additional context

None.

**Comment by Planeshifter** [comment]
This can be accomplished already.  One may something akin to the following:

```jsx
<DataExplorer 
    data={fueleconomy} 
    dataInfo={session.isOwner() ? fueleconomy_info_instructor : fueleconomy_info}
...
  ```

The `session.isOwner` function returns a boolean indicating whether the current user is a course owner. The ternary
`condition ? a : b`  will check whether the supplied condition is true and if so, assign the value `a` , and `b` otherwise. So we can have two `dataInfo` files loaded in the preamble and then use the appropriate one via code like the above.
