### ISSUE TITLE
[Bug]: qqplot not correct

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#3194]
### Description

go to:  https://isle.stat.cmu.edu/36-200-spring23/swimmers/  -> toolbox -> tests -> simple linear regression -> outcome = *improvement* -> explanatory = *pessimism* -> generate.

Then look at the diagnostics.

ISLE's qqplot looks like this:
![image](https://user-images.githubusercontent.com/31780210/230480384-c7b786bd-1191-4164-a632-77131075bf31.png)

That qqplot is wrong.  The diagonal only extends down to about y=-0.1, and the points are far too close to the line.

Here's R's qqplot from running the same model:
![image](https://user-images.githubusercontent.com/31780210/230480806-901942ee-3498-490b-b893-1dda5b493435.png)

### To Reproduce

see above

### Version

the lesson was uploaded with editor version 0.76.22

### Link to ISLE lesson

see above

### What browsers are you seeing the problem on?

Firefox

### What browser version?

111.0.1

### Additional context

The residual plot is correct, it exactly matches R's residual plot.  But something's clearly wrong with the qqplot.

**Comment by Planeshifter** [comment]
The ISLE residual qq-plot is currently not plotting standardized residuals, but the raw residuals. That seems to explain the difference in the visual appearance. I think we want to update the code to display standardized residuals, so I will leave this issue open and close it only once that change has been made.

**Comment by gweinberg** [comment]
ah.  Yeah however most other qqplot utilities do it.

**Comment by Planeshifter** [comment]
Changed it so that standardized residuals are displayed going forward.
