### ISSUE TITLE
[Bug]: variable descriptions pushed off side of panel due to long variable names

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#3200]
### Description

go to https://isle.stat.cmu.edu/36-200-spring23/covid_project2/ and click on the "Description' button.  Then, along the right-hand side of the description pop up, part of the text exceeds the white background, due to long variable names:
![image](https://user-images.githubusercontent.com/31780210/230665729-d6a8c25c-bc52-4cd0-a7cb-cbea09ce9c4a.png)

### Expected behavior

a fix might be to put the variable descriptions **below** the dataset description instead of along side.

### To Reproduce

see above

### Version

0.76.22, Windows NT

### Link to ISLE lesson

see above

### What browsers are you seeing the problem on?

Firefox

**Comment by Planeshifter** [comment]
This should be resolved now.
