### ISSUE TITLE
[Bug]: number question removes negative sign if a leading zero is typed; and removes negative and decimal if placeholding zero is typed.

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#3222]
### Description

**Bug 1**:
in NumberQuestion, if the answer is supposed to be a negative proper decimal like -0.1, it would be natural (and, indeed, mathematically proper) to type the leading zero; i.e., to type the negative sign, then the leading zero, then the decimal point, then the 1.

However, if you type the leading zero, it removes the negative sign.

**Bug 2** (I think this is a more severe bug than bug 1):
In NumberQuestion, if the answer is supposed to be a negative proper decimal like -0.01, with a placeholding zero, then (attempting to work around bug 1), even if you type:  negative sign, decimal point, and then the placeholding zero, as soon as you type the zero it removes the negative sign and the decimal point.

For instance: https://isle.stat.cmu.edu/36-200-first-summer-23/lab11/ -> the question labeled "4b" (the second number question on the 4th "page"), the answer is supposed to be  -0.0117, but if you type:  negative sign, decimal point, zero, as soon as you type the zero it removes the negative sign and the decimal point.

### Expected behavior

NumberQuestion needs to accept leading zeros and placeholding zeros, without removing previous negative signs, decimal points, or previous digits 

### To Reproduce

see above

### Version

0.76.22, Windows NT

### Link to ISLE lesson

see above

### What browsers are you seeing the problem on?

Firefox

### What browser version?

112.0.1

**Comment by Planeshifter** [comment]
Many thanks for filing this issue! A fix has meanwhile been implemented.

**Comment by gweinberg** [comment]
nice, looking forward to the new editor update
