### ISSUE TITLE
markdown compatibility?

### ISSUE THREAD

**Issue by ciaran-evans** [isle-project/isle-editor#326]
Looks like some Markdown syntax doesn't parse as expected in the editor. For example, to include a url link `<https://www.youtube.com/watch?v=wPqtzj5VZus>` should work, but doesn't; to get that link need to do something like 
`[https://www.youtube.com/watch?v=wPqtzj5VZus](https://www.youtube.com/watch?v=wPqtzj5VZus)`

**Comment by Planeshifter** [comment]
@ciaran-evans This problem is now fixed, thanks for finding it and letting me know about it!
