### ISSUE TITLE
[Bug]: barchart Y axis wrongly remains labeled "proportion" after "group by" is de-selected

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#3289]
### Description
Do the following:
https://isle.stat.cmu.edu/36-200-first-summer-23/lab2/ -> toolbox -> plots -> barchart -> variable=Rash -> group-by = Dengue -> check "relative frequences inside each group" -> generate **but keep toolbox open** -> with "relative frequencies inside each group" still checked, X-out the "group by" variable so that you're only plotting Rash -> generate.

Then, a barchart of counts for "Rash" is produced as expected, and the heights of the bars are correctly counts as seen by mousing-over, but the Y axis is wrongly labeled "proportion."

[Evidently, the widget still "thinks" that "relative frequencies inside each group" is selected behind the scenes, so it's still labeling the Y axis as "proportion" even though it's now count.]

### Expected behavior

when you X-out the 'group by' variable, the widget needs to no longer internally apply the "relative frequencies inside each group".

### To Reproduce

see above

### Version

0.76.22, Windows NT

### Link to ISLE lesson

see above

### What browsers are you seeing the problem on?

Firefox

### What browser version?

113.0.1

**Comment by Planeshifter** [comment]
Thanks! This has now been fixed.
