### ISSUE TITLE
[Bug]: copy/paste duplication of word "value" on one sample proportion test panel

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#3292]
### Description

![image](https://github.com/isle-project/isle-editor/assets/31780210/2dda691c-fe4f-4f2f-a627-03af50c0488d)

### To Reproduce

toolbox -> one sample proportion test

### Version

0.76.23

### What browsers are you seeing the problem on?

Firefox

### What browser version?

113.0.1

**Comment by Planeshifter** [comment]
Fixed, thanks for reporting!
