### ISSUE TITLE
[Bug]: copy/paste duplicate colon in one sample proprortion "Category of interest"

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#3293]
### Description

![image](https://github.com/isle-project/isle-editor/assets/31780210/06e114a6-ec99-4120-80ef-5262a8a654b5)

### To Reproduce

see above

### Version

0.76.23

### What browsers are you seeing the problem on?

Firefox

### What browser version?

113.0.1

**Comment by Planeshifter** [comment]
Fixed, thanks for reporting!
