### ISSUE TITLE
non-english characters?

### ISSUE THREAD

**Issue by ciaran-evans** [isle-project/isle-editor#334]
Filing this issue just because I don't know what the answer is. Would be nice for ISLE to support non-english characters, and it looks like it already does (at least in part - I tried some HTML spanish characters and they seemed to work). To what extent will non-english characters work, and what is the best way to write them - would foreign keyboards work directly, or do codes like `&aacute;` need to be typed in?

**Comment by Planeshifter** [comment]
For future reference: ISLE lessons are HTML pages supporting all Unicode characters without one having to resort to numeric references through UTF-8 encoding. One should be able to directly use the characters inside the editor and have them render correctly in the lessons.
