### ISSUE TITLE
unable to use "save file as" for new documents

### ISSUE THREAD

**Issue by ciaran-evans** [isle-project/isle-editor#358]
When I try to use "Save File As" on a new, untitled document, I get a javascript error. I instead have to use "Save File", which then lets me enter a name for the file and choose a location. "Save File As" does appear to work on already saved ISLE files.

**Comment by Planeshifter** [comment]
Thanks for filing this issue! Fixed in a27fa70beee2ab8111d7c4e0245e76cf7090dcd2.
