### ISSUE TITLE
request data explorer option for "DownloadData = FALSE"

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#3584]
### Problem

I would like a new option to be added to data explorer so I can disable/remove the "download data" button, since with the advent of LLMs, more students are able to upload the csv's into LLMs and have them do their reports for them.

### Solution

an extra option in data explorer, called, for instance, DownloadData, that can take either "TRUE" or "FALSE" (default would probably be true)

### Additional context

None.

**Comment by Planeshifter** [comment]
@gweinberg Luckily this should already be possible. Try setting attribute `dataTableProps={{ disableDownload: true }}` on the data explorer.

**Comment by gweinberg** [comment]
oh nice, thanks.  I notice that "disableDownload" isn't in the list of dataTableProps

**Comment by Planeshifter** [comment]
`dataTableProps` is just passed through to the underlying `<DataTable />` component, so all  properties that exist on that component should work.
