### ISSUE TITLE
Display units in data table

### ISSUE THREAD

**Issue by frank113** [isle-project/isle-editor#427]
**Is your feature request related to a problem? Please describe.**

This request is not an issue or in response to a bug. The request comes from Professor Weinberg's question. 

**Describe the solution you'd like**

A tool tip of sorts, or a field near the column name in the data-table.

**Describe alternatives you've considered**

We could place the units in the variable descriptions.

**Additional context**

**Comment by Planeshifter** [comment]
Closing as this should be handled by choosing appropriate variable descriptions and no new development is needed to support this.
