### ISSUE TITLE
Counter for question queue is off

### ISSUE THREAD

**Issue by frank113** [isle-project/isle-editor#434]
**Describe the bug**
When examining the status bar, the number of questions in the queue displays the negative of the number of individuals viewing the lesson as students. When a student submits a question, 
the queue correctly increments by 1.

**To Reproduce**
1. Go to an active lesson with an active question queue.
2. View the queue from either the perspective of a student or teacher.

**Expected behavior**
I expect the question queue to start at 0. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS Mojave 10.14.6. MacBook Pro Mid-2015 13 inch Retina
 - Browser: Chrome
 - Version: 76.0.3809.100 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**
I am not sure if the number is the true negative, but it appears to be so based on anecdotal evidence about it when many and few students were viewing the lab.

**Comment by Planeshifter** [comment]
This issue should now be fixed (per commit 0a262d9234c2c651b2427af640b9270149fff1ca).
