### ISSUE TITLE
Show toolbox not popping up when multiple data sets in a slider

### ISSUE THREAD

**Issue by jspm-kymetis** [isle-project/isle-editor#881]
**Describe the bug**

**To Reproduce**
1. Go to https://isle.kymetis.com/nugent/Multiplicity-Berdine-TTU/#/1
2. Click on Show Toolbox

**Expected behavior**
Toolbox shows

**Screenshots**
![image](https://user-images.githubusercontent.com/62388791/79906036-22093680-83e5-11ea-9c21-c1767c3af2a5.png)

**Desktop (please complete the following information):**
Google Chrome Browser - Version 80.0.3987.163 (Official Build) (64-bit)
OS Name	Microsoft Windows 10 Pro
Version	10.0.18363 Build 18363
System Type	x64-based PC
System SKU	LENOVO_MT_20FQ_BU_Think_FM_ThinkPad X1 Yoga 1st
Processor	Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz, 2808 Mhz, 2 Core(s), 4 Logical BIOS Version/Date	LENOVO N1FET66W (1.40 ), 11/20/2018

**Additional context**
Toolbox shows on the second data set in the slider:
![image](https://user-images.githubusercontent.com/62388791/79906240-70b6d080-83e5-11ea-8192-74dc1023a0e9.png)

**Comment by Planeshifter** [comment]
Thanks for filing this issue! Can reproduce and will investigate shortly.

**Comment by Planeshifter** [comment]
This issue has been resolved through commit 92ec730cb734b99f11cdbc23f5854e8abfb8e8d6.

A solution was obtained by attaching the toolbox directly to the lesson div of the document and not have it as a child element of its parent.
